import { Injectable, Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

export interface BusinessDocument {
  id: string;
  slug: string;
  name: string;
  description: string;
  categoryId: string;
  categoryName: string;
  /** The category's vocabulary — what makes a scraped shop findable by what it sells. */
  categoryTerms: string[];
  /** What the shop itself says it stocks. Reaches the shelf, where the category cannot. */
  keywords: string[];
  businessType: string;
  claimStatus: string;
  cityId: string | null;
  cityName: string | null;
  localityName: string | null;
  pincodeCode: string | null;
  isVerified: boolean;
  isClaimed: boolean;
  _geo?: { lat: number; lng: number };
}

/**
 * Businesses in their own search index.
 *
 * Until now only listings were searchable, so the platform's central promise did not work:
 * somebody searching "biryani" could find a classified ad for a rice cooker but never the
 * hotel down the road. Four million imported businesses would have been invisible.
 *
 * A separate index rather than a shared one with a type facet. Two reasons. Relevance
 * scoring is per index, so mixing four million businesses into the listings index would
 * dilute every listing query — a shop and a for-sale ad are not competing to answer the same
 * question. And the vision asks for results grouped by kind, which is natural with two
 * indexes and awkward with one.
 *
 * The rules are otherwise deliberately identical to the listings index: the same stop words,
 * the same typo tolerance, the same matching strategy. A user cannot see which index
 * answered them, so any difference in how forgiving the two are would read as the search
 * being unpredictable.
 */
/**
 * How many matching rows are ranked before the best are chosen.
 *
 * A bare nationwide query on a common word can match tens of thousands of businesses, and
 * `ts_rank` has to score every one of them before sorting. Finding them is indexed and
 * fast; scoring them is not. This bounds that work.
 *
 * It only ever engages on a query with no city, pincode or radius, which the app does not
 * send — and a person who has genuinely asked for "every medical shop in India, ranked" is
 * better served by a fast answer from the first few thousand than by a slow one from all.
 */
const RANKING_CANDIDATE_CAP = 5_000;

@Injectable()
export class BusinessSearchService {
  private readonly logger = new Logger(BusinessSearchService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Kept so callers do not change. There is nothing to do.
   *
   * `searchDoc` is generated by Postgres from the row itself, so writing the row *is*
   * indexing it. The previous implementation enqueued work here, and a silent queue is
   * how the index came to hold 400 of 3.4 million businesses.
   */
  indexBusiness(_businessId: string): Promise<void> {
    return Promise.resolve();
  }

  /** Same: deleting the row removes its document, because they are the same thing. */
  removeBusiness(_businessId: string): Promise<void> {
    return Promise.resolve();
  }

  async search(params: {
    query: string;
    cityId?: string;
    pincode?: string;
    categoryId?: string;
    businessType?: string;
    latitude?: number;
    longitude?: number;
    radiusKm?: number;
    page: number;
    limit: number;
  }): Promise<{ ids: string[]; total: number }> {
    const query = params.query.trim();
    const offset = (params.page - 1) * params.limit;
    const hasGeo = params.latitude !== undefined && params.longitude !== undefined;
    const radiusMetres = (params.radiusKm ?? 10) * 1000;

    const where = [
      Prisma.sql`b."deletedAt" IS NULL`,
      Prisma.sql`b."isActive"`,
      query ? Prisma.sql`b."searchDoc" @@ plainto_tsquery('simple', ${query})` : Prisma.sql`TRUE`,
      params.cityId ? Prisma.sql`b."cityId" = ${params.cityId}::uuid` : Prisma.sql`TRUE`,
      params.pincode ? Prisma.sql`b."pincodeCode" = ${params.pincode}` : Prisma.sql`TRUE`,
      params.categoryId
        ? Prisma.sql`b."categoryId" = ${params.categoryId}::uuid`
        : Prisma.sql`TRUE`,
      params.businessType
        ? Prisma.sql`b."businessType"::text = ${params.businessType}`
        : Prisma.sql`TRUE`,
      hasGeo
        ? Prisma.sql`ST_DWithin(b."geo", ST_MakePoint(${params.longitude}, ${params.latitude})::geography, ${radiusMetres})`
        : Prisma.sql`TRUE`,
    ];

    const rows = await this.prisma.$queryRaw<Array<{ id: string; total: bigint }>>(
      Prisma.sql`
        WITH candidates AS (
          SELECT b.id, b."searchDoc", b."geo"
          FROM "businesses" b
          WHERE ${Prisma.join(where, ' AND ')}
          -- Ranking is what costs, not finding. "medical" matches 30,706 businesses
          -- nationwide and scoring every one took 2.6 seconds; the index found them in
          -- milliseconds. Capping the set first bounds the worst case, and only a query
          -- with no city, pincode or radius ever reaches the cap — the app always sends
          -- one, so ordinary searches are unaffected and still see everything.
          LIMIT ${RANKING_CANDIDATE_CAP}
        ),
        matched AS (
          SELECT c.id,
                 ${query ? Prisma.sql`ts_rank(c."searchDoc", plainto_tsquery('simple', ${query}))` : Prisma.sql`0`} AS rank,
                 ${hasGeo ? Prisma.sql`ST_Distance(c."geo", ST_MakePoint(${params.longitude}, ${params.latitude})::geography)` : Prisma.sql`0`} AS metres
          FROM candidates c
        )
        SELECT id, count(*) OVER () AS total
        FROM matched
        -- Relevance first, then distance. The nearest irrelevant shop is still irrelevant.
        ORDER BY rank DESC, metres ASC
        LIMIT ${params.limit} OFFSET ${offset}`,
    );

    if (rows.length > 0 || !query || query.length < 4) {
      return { ids: rows.map((row) => row.id), total: Number(rows[0]?.total ?? 0) };
    }

    // Nothing matched exactly. `plainto_tsquery` is exact-token, so "medicl" finds nothing
    // where Meilisearch would have forgiven it. Trigram similarity is the fallback, and it
    // runs only here — never on the common path, because it cannot use the tsvector index.
    return this.fuzzySearch(params, query, offset);
  }

  /**
   * Last resort for a misspelling, on name only.
   *
   * Deliberately narrower than the strict query: keywords and source ids are noisy under
   * fuzzy matching, and a wrong result the user cannot explain is worse than none.
   */
  private async fuzzySearch(
    params: {
      cityId?: string;
      pincode?: string;
      categoryId?: string;
      businessType?: string;
      latitude?: number;
      longitude?: number;
      radiusKm?: number;
      limit: number;
    },
    query: string,
    offset: number,
  ): Promise<{ ids: string[]; total: number }> {
    const hasGeo = params.latitude !== undefined && params.longitude !== undefined;
    const radiusMetres = (params.radiusKm ?? 10) * 1000;

    const where = [
      Prisma.sql`b."deletedAt" IS NULL`,
      Prisma.sql`b."isActive"`,
      Prisma.sql`b."name" % ${query}`,
      params.cityId ? Prisma.sql`b."cityId" = ${params.cityId}::uuid` : Prisma.sql`TRUE`,
      params.pincode ? Prisma.sql`b."pincodeCode" = ${params.pincode}` : Prisma.sql`TRUE`,
      params.categoryId
        ? Prisma.sql`b."categoryId" = ${params.categoryId}::uuid`
        : Prisma.sql`TRUE`,
      params.businessType
        ? Prisma.sql`b."businessType"::text = ${params.businessType}`
        : Prisma.sql`TRUE`,
      hasGeo
        ? Prisma.sql`ST_DWithin(b."geo", ST_MakePoint(${params.longitude}, ${params.latitude})::geography, ${radiusMetres})`
        : Prisma.sql`TRUE`,
    ];

    const rows = await this.prisma.$queryRaw<Array<{ id: string; total: bigint }>>(
      Prisma.sql`
        WITH matched AS (
          SELECT b.id, similarity(b."name", ${query}) AS score
          FROM "businesses" b
          WHERE ${Prisma.join(where, ' AND ')}
        )
        SELECT id, count(*) OVER () AS total
        FROM matched
        ORDER BY score DESC
        LIMIT ${params.limit} OFFSET ${offset}`,
    );

    return { ids: rows.map((row) => row.id), total: Number(rows[0]?.total ?? 0) };
  }

  /**
   * Rebuilds the whole index from the database.
   *
   * Builds into a replacement and swaps, so search is never briefly empty. The swap is
   * verified before the old index is dropped: a swap that silently does nothing once left
   * the live index empty while the API reported it as healthy, and deleting the replacement
   * at that point destroys the only good copy.
   */
  /**
   * Nothing to rebuild, so this only reports what exists.
   *
   * The endpoint and its tests stay, because "rebuild the index" is still a reasonable
   * thing for an administrator to ask for — the honest answer is now that it is already
   * true by construction.
   */
  async reindexAll(): Promise<{ indexed: number }> {
    const indexed = await this.prisma.business.count({
      where: { deletedAt: null, isActive: true },
    });
    this.logger.log(`Business search is a generated column; ${indexed} businesses are searchable`);
    return { indexed };
  }

  /**
   * Drift is no longer expressible, which is the whole point of the change.
   *
   * `indexedDocuments` equals `businesses` by definition. It is still reported so the
   * admin console keeps working and so the difference is visibly, permanently zero.
   */
  async status(): Promise<{ available: boolean; indexedDocuments?: number; businesses: number }> {
    const businesses = await this.prisma.business.count({
      where: { deletedAt: null, isActive: true },
    });
    return { available: true, indexedDocuments: businesses, businesses };
  }
}
