import { Injectable, Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

export interface BusinessDocument {
  id: string;
  slug: string;
  name: string;
  description: string;
  categoryId: string;
  categoryName: string;
  /** The category's vocabulary — what makes a scraped shop findable by what it sells. */
  categoryTerms: string[];
  /** What the shop itself says it stocks. Reaches the shelf, where the category cannot. */
  keywords: string[];
  businessType: string;
  claimStatus: string;
  cityId: string | null;
  cityName: string | null;
  localityName: string | null;
  pincodeCode: string | null;
  isVerified: boolean;
  isClaimed: boolean;
  _geo?: { lat: number; lng: number };
}

/**
 * Businesses in their own search index.
 *
 * Until now only listings were searchable, so the platform's central promise did not work:
 * somebody searching "biryani" could find a classified ad for a rice cooker but never the
 * hotel down the road. Four million imported businesses would have been invisible.
 *
 * A separate index rather than a shared one with a type facet. Two reasons. Relevance
 * scoring is per index, so mixing four million businesses into the listings index would
 * dilute every listing query — a shop and a for-sale ad are not competing to answer the same
 * question. And the vision asks for results grouped by kind, which is natural with two
 * indexes and awkward with one.
 *
 * The rules are otherwise deliberately identical to the listings index: the same stop words,
 * the same typo tolerance, the same matching strategy. A user cannot see which index
 * answered them, so any difference in how forgiving the two are would read as the search
 * being unpredictable.
 */
/**
 * How many matching rows are ranked before the best are chosen.
 *
 * A bare nationwide query on a common word can match tens of thousands of businesses, and
 * `ts_rank` has to score every one of them before sorting. Finding them is indexed and
 * fast; scoring them is not. This bounds that work.
 *
 * It only ever engages on a query with no city, pincode or radius, which the app does not
 * send — and a person who has genuinely asked for "every medical shop in India, ranked" is
 * better served by a fast answer from the first few thousand than by a slow one from all.
 */
const RANKING_CANDIDATE_CAP = 5_000;

@Injectable()
export class BusinessSearchService {
  private readonly logger = new Logger(BusinessSearchService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Kept so callers do not change. There is nothing to do.
   *
   * `searchDoc` is generated by Postgres from the row itself, so writing the row *is*
   * indexing it. The previous implementation enqueued work here, and a silent queue is
   * how the index came to hold 400 of 3.4 million businesses.
   */
  indexBusiness(_businessId: string): Promise<void> {
    return Promise.resolve();
  }

  /** Same: deleting the row removes its document, because they are the same thing. */
  removeBusiness(_businessId: string): Promise<void> {
    return Promise.resolve();
  }

  /**
   * Turns what somebody typed into a tsquery that forgives a plural.
   *
   * `plainto_tsquery` is exact-token and the dictionary is `simple`, which does no
   * stemming — deliberately, so "Medicals" does not collapse to "medic". The cost was
   * that "medical shops" found 3 businesses where "medical shop" found 6, because no
   * shop is named "Shops".
   *
   * So the plural is stripped from the *query* and a prefix match is added: "shops"
   * becomes `shop:*`, which reaches Shop, Shops and Shopping. On the real data that took
   * "medical shops" from 3 matches to 621.
   *
   * Prefix only from four characters. `car:*` would drag in carpenter and cargo, and a
   * search that returns confidently wrong results is worse than one that returns few.
   *
   * Tokens are split on anything that is not a letter or digit, which also removes every
   * character tsquery treats as an operator — `&`, `|`, `!`, `(`, `)`, `:` and `*` — so a
   * query cannot reach the parser as syntax.
   */
  private toPrefixQuery(query: string): string | null {
    const tokens = query
      .toLowerCase()
      .split(/[^\p{L}\p{N}]+/u)
      .filter((token) => token.length > 0);

    if (tokens.length === 0) return null;

    return tokens
      .map((token) => {
        const singular = token.length > 4 && token.endsWith('s') ? token.slice(0, -1) : token;
        return singular.length >= 4 ? `${singular}:*` : singular;
      })
      .join(' & ');
  }

  async search(params: {
    query: string;
    cityId?: string;
    pincode?: string;
    categoryId?: string;
    businessType?: string;
    latitude?: number;
    longitude?: number;
    radiusKm?: number;
    page: number;
    limit: number;
  }): Promise<{ ids: string[]; total: number }> {
    const query = params.query.trim();
    const tsquery = query ? this.toPrefixQuery(query) : null;
    const offset = (params.page - 1) * params.limit;
    const hasGeo = params.latitude !== undefined && params.longitude !== undefined;
    const radiusMetres = (params.radiusKm ?? 10) * 1000;

    const where = [
      Prisma.sql`b."deletedAt" IS NULL`,
      Prisma.sql`b."isActive"`,
      tsquery ? Prisma.sql`b."searchDoc" @@ to_tsquery('simple', ${tsquery})` : Prisma.sql`TRUE`,
      params.cityId ? Prisma.sql`b."cityId" = ${params.cityId}::uuid` : Prisma.sql`TRUE`,
      params.pincode ? Prisma.sql`b."pincodeCode" = ${params.pincode}` : Prisma.sql`TRUE`,
      params.categoryId
        ? Prisma.sql`b."categoryId" = ${params.categoryId}::uuid`
        : Prisma.sql`TRUE`,
      params.businessType
        ? Prisma.sql`b."businessType"::text = ${params.businessType}`
        : Prisma.sql`TRUE`,
      hasGeo
        ? Prisma.sql`ST_DWithin(b."geo", ST_MakePoint(${params.longitude}, ${params.latitude})::geography, ${radiusMetres})`
        : Prisma.sql`TRUE`,
    ];

    const rows = await this.prisma.$queryRaw<Array<{ id: string; total: bigint }>>(
      Prisma.sql`
        WITH candidates AS (
          SELECT b.id, b."searchDoc", b."geo"
          FROM "businesses" b
          WHERE ${Prisma.join(where, ' AND ')}
          -- Ranking is what costs, not finding. "medical" matches 30,706 businesses
          -- nationwide and scoring every one took 2.6 seconds; the index found them in
          -- milliseconds. Capping the set first bounds the worst case.
          --
          -- The cap engages whenever the *filtered* count exceeds it, city filter or not —
          -- a common word in a large metro will reach it — so which rows it keeps has to be
          -- decided rather than left to the planner. A bare LIMIT takes an arbitrary
          -- 5,000, and PostgreSQL does not promise the same 5,000 twice: a parallel scan
          -- does not assemble its workers' output identically. Page two was therefore drawn
          -- from a different candidate set than page one, so a shop appeared on both while
          -- another was never shown. Ordering by id makes the window stable across the
          -- requests that page through it.
          ORDER BY b.id
          LIMIT ${RANKING_CANDIDATE_CAP}
        ),
        matched AS (
          SELECT c.id,
                 ${tsquery ? Prisma.sql`ts_rank(c."searchDoc", to_tsquery('simple', ${tsquery}))` : Prisma.sql`0`} AS rank,
                 ${hasGeo ? Prisma.sql`ST_Distance(c."geo", ST_MakePoint(${params.longitude}, ${params.latitude})::geography)` : Prisma.sql`0`} AS metres
          FROM candidates c
        )
        SELECT id, count(*) OVER () AS total
        FROM matched
        -- Relevance first, then distance. The nearest irrelevant shop is still irrelevant.
        --
        -- id last, for the same reason the listing queries carry a tie-breaker: without a
        -- keyword every rank is 0 and without coordinates every distance is 0, so every row
        -- ties and the order is whatever the planner returns — which is not the same order
        -- on the next request for the next page.
        ORDER BY rank DESC, metres ASC, id ASC
        LIMIT ${params.limit} OFFSET ${offset}`,
    );

    // `offset === 0` as well as the length check: an empty page four is the end of the
    // results, not a misspelling, and falling through to the fuzzy path there would answer a
    // request for "more of the same" with a different set of shops entirely.
    if (rows.length > 0 || !query || query.length < 4 || offset > 0) {
      return { ids: rows.map((row) => row.id), total: Number(rows[0]?.total ?? 0) };
    }

    // Nothing matched even with prefixes, so this is a misspelling rather than a plural
    // where Meilisearch would have forgiven it. Trigram similarity is the fallback, and it
    // runs only here — never on the common path, because it cannot use the tsvector index.
    return this.fuzzySearch(params, query, offset);
  }

  /**
   * Last resort for a misspelling, on name only.
   *
   * Deliberately narrower than the strict query: keywords and source ids are noisy under
   * fuzzy matching, and a wrong result the user cannot explain is worse than none.
   */
  private async fuzzySearch(
    params: {
      cityId?: string;
      pincode?: string;
      categoryId?: string;
      businessType?: string;
      latitude?: number;
      longitude?: number;
      radiusKm?: number;
      limit: number;
    },
    query: string,
    offset: number,
  ): Promise<{ ids: string[]; total: number }> {
    const hasGeo = params.latitude !== undefined && params.longitude !== undefined;
    const radiusMetres = (params.radiusKm ?? 10) * 1000;

    const where = [
      Prisma.sql`b."deletedAt" IS NULL`,
      Prisma.sql`b."isActive"`,
      Prisma.sql`b."name" % ${query}`,
      params.cityId ? Prisma.sql`b."cityId" = ${params.cityId}::uuid` : Prisma.sql`TRUE`,
      params.pincode ? Prisma.sql`b."pincodeCode" = ${params.pincode}` : Prisma.sql`TRUE`,
      params.categoryId
        ? Prisma.sql`b."categoryId" = ${params.categoryId}::uuid`
        : Prisma.sql`TRUE`,
      params.businessType
        ? Prisma.sql`b."businessType"::text = ${params.businessType}`
        : Prisma.sql`TRUE`,
      hasGeo
        ? Prisma.sql`ST_DWithin(b."geo", ST_MakePoint(${params.longitude}, ${params.latitude})::geography, ${radiusMetres})`
        : Prisma.sql`TRUE`,
    ];

    const rows = await this.prisma.$queryRaw<Array<{ id: string; total: bigint }>>(
      Prisma.sql`
        WITH matched AS (
          SELECT b.id, similarity(b."name", ${query}) AS score
          FROM "businesses" b
          WHERE ${Prisma.join(where, ' AND ')}
        )
        SELECT id, count(*) OVER () AS total
        FROM matched
        -- Tie-break on id: similarity scores collide freely, and without it the same query
        -- returns a different arrangement each time it is paged.
        ORDER BY score DESC, id ASC
        LIMIT ${params.limit} OFFSET ${offset}`,
    );

    return { ids: rows.map((row) => row.id), total: Number(rows[0]?.total ?? 0) };
  }

  /**
   * Rebuilds the whole index from the database.
   *
   * Builds into a replacement and swaps, so search is never briefly empty. The swap is
   * verified before the old index is dropped: a swap that silently does nothing once left
   * the live index empty while the API reported it as healthy, and deleting the replacement
   * at that point destroys the only good copy.
   */
  /**
   * Nothing to rebuild, so this only reports what exists.
   *
   * The endpoint and its tests stay, because "rebuild the index" is still a reasonable
   * thing for an administrator to ask for — the honest answer is now that it is already
   * true by construction.
   */
  async reindexAll(): Promise<{ indexed: number }> {
    const indexed = await this.prisma.business.count({
      where: { deletedAt: null, isActive: true },
    });
    this.logger.log(`Business search is a generated column; ${indexed} businesses are searchable`);
    return { indexed };
  }

  /**
   * Drift is no longer expressible, which is the whole point of the change.
   *
   * `indexedDocuments` equals `businesses` by definition. It is still reported so the
   * admin console keeps working and so the difference is visibly, permanently zero.
   */
  async status(): Promise<{ available: boolean; indexedDocuments?: number; businesses: number }> {
    const businesses = await this.prisma.business.count({
      where: { deletedAt: null, isActive: true },
    });
    return { available: true, indexedDocuments: businesses, businesses };
  }
}
