import 'server-only';
import { headers } from 'next/headers';

export const QUEUE_COPY = {
  en: {
    claimsNav: 'Business claims',
    claimsKicker: 'Ownership review',
    claimsTitle: 'Business claims',
    claimsBody:
      'Review the oldest ownership requests first. Approval transfers the business profile to the claimant.',
    waiting: '{count} waiting',
    emptyTitle: 'No claims waiting',
    emptyBody: 'New ownership claims will appear here for review.',
    loadError: 'Could not load business claims.',
    business: 'Business',
    claimant: 'Claimant',
    source: 'Imported source',
    evidence: 'Claimant’s evidence',
    submitted: 'Submitted',
    phone: 'Contact',
    email: 'Email',
    noContact: 'Not supplied',
    setup: 'Business setup',
    offering: 'Offering',
    matchedSignals: 'Matched signals',
    noSignals: 'No verified signals matched',
    location: 'Claim location',
    accurateTo: 'Accurate to {metres} m',
    locationMissing: 'Not shared',
    auto: 'Auto-check eligible',
    openProfile: 'Open public profile',
    rejectReason: 'What should the shopkeeper correct?',
    rejectHint: 'Be specific. This message is sent to the claimant.',
    rejectPlaceholder: 'Example: Upload a document showing the business name and address.',
    reject: 'Reject with guidance',
    approve: 'Approve claim',
    working: 'Saving…',
    approved: 'Claim approved and ownership transferred.',
    rejected: 'Claim rejected and guidance sent.',
    missingClaim: 'Claim identifier is missing.',
    reasonShort: 'Write at least 5 characters so the claimant can act on the rejection.',
    approveError: 'Could not approve this claim.',
    rejectError: 'Could not reject this claim.',
    previous: 'Previous',
    next: 'Next',
    pageOf: 'Page {page} of {total}',
    scaleShop: 'Individual shop',
    scaleHome: 'Home business',
    scaleEnterprise: 'Enterprise',
    products: 'Products',
    services: 'Services',
    both: 'Products and services',
    unknown: 'Not specified',
  },
  hi: {
    claimsNav: 'व्यवसाय दावे',
    claimsKicker: 'मालिकाना समीक्षा',
    claimsTitle: 'व्यवसाय दावे',
    claimsBody:
      'सबसे पुराने मालिकाना अनुरोध पहले जाँचें। मंज़ूरी से व्यवसाय प्रोफ़ाइल दावेदार को मिलती है।',
    waiting: '{count} प्रतीक्षा में',
    emptyTitle: 'कोई दावा प्रतीक्षा में नहीं',
    emptyBody: 'नए मालिकाना दावे समीक्षा के लिए यहाँ दिखेंगे।',
    loadError: 'व्यवसाय दावे लोड नहीं हो सके।',
    business: 'व्यवसाय',
    claimant: 'दावेदार',
    source: 'आयातित स्रोत',
    evidence: 'दावेदार का प्रमाण',
    submitted: 'भेजने का समय',
    phone: 'संपर्क',
    email: 'ईमेल',
    noContact: 'नहीं दिया',
    setup: 'व्यवसाय का स्वरूप',
    offering: 'पेशकश',
    matchedSignals: 'मिले हुए संकेत',
    noSignals: 'कोई सत्यापित संकेत नहीं मिला',
    location: 'दावे की लोकेशन',
    accurateTo: '{metres} मीटर तक सटीक',
    locationMissing: 'साझा नहीं की',
    auto: 'ऑटो-जाँच योग्य',
    openProfile: 'सार्वजनिक प्रोफ़ाइल खोलें',
    rejectReason: 'दुकानदार को क्या सुधारना चाहिए?',
    rejectHint: 'स्पष्ट लिखें। यह संदेश दावेदार को भेजा जाएगा।',
    rejectPlaceholder: 'उदाहरण: व्यवसाय का नाम और पता दिखाने वाला दस्तावेज़ अपलोड करें।',
    reject: 'मार्गदर्शन के साथ अस्वीकार करें',
    approve: 'दावा मंज़ूर करें',
    working: 'सहेज रहे हैं…',
    approved: 'दावा मंज़ूर हुआ और मालिकाना स्थानांतरित हो गया।',
    rejected: 'दावा अस्वीकार हुआ और मार्गदर्शन भेज दिया गया।',
    missingClaim: 'दावे की पहचान उपलब्ध नहीं है।',
    reasonShort: 'कम से कम 5 अक्षर लिखें ताकि दावेदार उस पर काम कर सके।',
    approveError: 'यह दावा मंज़ूर नहीं हो सका।',
    rejectError: 'यह दावा अस्वीकार नहीं हो सका।',
    previous: 'पिछला',
    next: 'अगला',
    pageOf: 'पेज {page} / {total}',
    scaleShop: 'एकल दुकान',
    scaleHome: 'घरेलू व्यवसाय',
    scaleEnterprise: 'उद्यम',
    products: 'उत्पाद',
    services: 'सेवाएँ',
    both: 'उत्पाद और सेवाएँ',
    unknown: 'नहीं बताया',
  },
  te: {
    claimsNav: 'వ్యాపార క్లెయిమ్‌లు',
    claimsKicker: 'యాజమాన్య పరిశీలన',
    claimsTitle: 'వ్యాపార క్లెయిమ్‌లు',
    claimsBody:
      'పాత యాజమాన్య అభ్యర్థనలను ముందుగా పరిశీలించండి. ఆమోదం వ్యాపార ప్రొఫైల్‌ను క్లెయిమెంట్‌కు బదిలీ చేస్తుంది.',
    waiting: '{count} వేచి ఉన్నాయి',
    emptyTitle: 'వేచి ఉన్న క్లెయిమ్‌లు లేవు',
    emptyBody: 'కొత్త యాజమాన్య క్లెయిమ్‌లు పరిశీలన కోసం ఇక్కడ కనిపిస్తాయి.',
    loadError: 'వ్యాపార క్లెయిమ్‌లను లోడ్ చేయలేకపోయాము.',
    business: 'వ్యాపారం',
    claimant: 'క్లెయిమెంట్',
    source: 'దిగుమతి మూలం',
    evidence: 'క్లెయిమెంట్ ఆధారం',
    submitted: 'పంపిన సమయం',
    phone: 'సంప్రదింపు',
    email: 'ఈమెయిల్',
    noContact: 'ఇవ్వలేదు',
    setup: 'వ్యాపార ఏర్పాటు',
    offering: 'అందించేది',
    matchedSignals: 'సరిపోలిన సంకేతాలు',
    noSignals: 'ధృవీకరించిన సంకేతాలు సరిపోలలేదు',
    location: 'క్లెయిమ్ లొకేషన్',
    accurateTo: '{metres} మీటర్ల వరకు ఖచ్చితం',
    locationMissing: 'షేర్ చేయలేదు',
    auto: 'ఆటో-చెక్‌కు అర్హత',
    openProfile: 'పబ్లిక్ ప్రొఫైల్ తెరవండి',
    rejectReason: 'దుకాణదారు ఏమి సరిచేయాలి?',
    rejectHint: 'స్పష్టంగా రాయండి. ఈ సందేశం క్లెయిమెంట్‌కు పంపబడుతుంది.',
    rejectPlaceholder: 'ఉదాహరణ: వ్యాపార పేరు, చిరునామా ఉన్న పత్రాన్ని అప్‌లోడ్ చేయండి.',
    reject: 'మార్గదర్శకంతో తిరస్కరించండి',
    approve: 'క్లెయిమ్ ఆమోదించండి',
    working: 'సేవ్ చేస్తోంది…',
    approved: 'క్లెయిమ్ ఆమోదించబడింది, యాజమాన్యం బదిలీ అయింది.',
    rejected: 'క్లెయిమ్ తిరస్కరించబడింది, మార్గదర్శకం పంపబడింది.',
    missingClaim: 'క్లెయిమ్ గుర్తింపు లేదు.',
    reasonShort: 'క్లెయిమెంట్ చర్య తీసుకోగలిగేలా కనీసం 5 అక్షరాలు రాయండి.',
    approveError: 'ఈ క్లెయిమ్‌ను ఆమోదించలేకపోయాము.',
    rejectError: 'ఈ క్లెయిమ్‌ను తిరస్కరించలేకపోయాము.',
    previous: 'మునుపటి',
    next: 'తదుపరి',
    pageOf: 'పేజీ {page} / {total}',
    scaleShop: 'వ్యక్తిగత షాప్',
    scaleHome: 'గృహ వ్యాపారం',
    scaleEnterprise: 'సంస్థ',
    products: 'ఉత్పత్తులు',
    services: 'సేవలు',
    both: 'ఉత్పత్తులు, సేవలు',
    unknown: 'పేర్కొనలేదు',
  },
} as const;

export type AdminQueueCopy = { [K in keyof typeof QUEUE_COPY.en]: string };
export type AdminQueueLocale = keyof typeof QUEUE_COPY;

export async function getAdminQueueCopy(): Promise<{
  copy: AdminQueueCopy;
  locale: AdminQueueLocale;
}> {
  const language = (await headers()).get('accept-language')?.toLowerCase() ?? '';
  const locale: AdminQueueLocale = language.startsWith('te')
    ? 'te'
    : language.startsWith('hi')
      ? 'hi'
      : 'en';
  return { copy: QUEUE_COPY[locale], locale };
}
