#!/usr/bin/env bash
# Regenerates the allowlist of category artwork that actually ships in public/.
# Run after adding or removing files in apps/web/public/icons/category-library/.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
dir="$root/apps/web/public/icons/category-library"
out="$root/apps/web/src/lib/category-artwork-manifest.ts"
{
  echo "// GENERATED by scripts/gen-category-artwork-manifest.sh - do not edit by hand."
  echo "//"
  echo "// The catalog builds an icon URL from a category slug, but only 183 of the ~1,588"
  echo "// category slugs have artwork. Without this allowlist every other category page asked"
  echo "// the browser (and Googlebot) for an icon that 404s, which next/image then reported as"
  echo "// \"The requested resource isn't a valid image ... received null\". Checking membership"
  echo "// here turns those into the shared fallback instead of a failed request."
  echo "export const CATEGORY_ARTWORK = new Set<string>(["
  ls "$dir" | sed 's/\.webp$//' | sort | sed "s/.*/  '&',/"
  echo "]);"
} > "$out"
echo "wrote $out ($(ls "$dir" | wc -l) entries)"
