export type PremiumCategoryBanner = Readonly<{
  desktop: string;
  mobile: string;
}>;

function banner(slug: string): PremiumCategoryBanner {
  return {
    desktop: `/banners/categories/${slug}-desktop.webp`,
    mobile: `/banners/categories/${slug}-mobile.webp`,
  };
}

const automobile = banner('automobile-services-v2');
const beauty = banner('beauty-wellness-v2');
const education = banner('education-training');

const categoryBanners: Readonly<Record<string, PremiumCategoryBanner>> = {
  'automobile services': automobile,
  'ayurveda & herbal': banner('ayurveda-herbal'),
  'bakeries & sweets': banner('bakeries-sweets-v5'),
  'bread & buns': banner('bread-buns'),
  'beauty & cosmetics': banner('beauty-cosmetics'),
  'beauty & wellness': beauty,
  'bike repair': banner('bike-repair'),
  'books, stationery & office': banner('books-stationery'),
  'cakes & pastries': banner('cakes-pastries'),
  'car repair': banner('car-repair'),
  chicken: banner('chicken'),
  'cleaning services': banner('cleaning-services'),
  'clothing stores': banner('clothing-stores'),
  colleges: banner('colleges'),
  'computer & laptop stores': banner('computer-laptop-stores'),
  'cooking oil & ghee': banner('cooking-oil-ghee'),
  'courier & parcel': banner('courier-parcel'),
  'dairy, bakery & eggs': banner('dairy-bakery-eggs'),
  'dry fruits & nuts': banner('dry-fruits-nuts'),
  eggs: banner('eggs'),
  'education & training': education,
  'electrical services': banner('electrical-services'),
  'electrical stores': banner('electrical-stores'),
  'electronics stores': banner('electronics-stores'),
  'event services': banner('event-services'),
  'ev charging stations': banner('ev-charging-stations'),
  'flour & atta': banner('flour-atta'),
  'fish & seafood': banner('fish-seafood'),
  'footwear stores': banner('footwear-stores'),
  'furniture stores': banner('furniture-stores'),
  'fruits & vegetables': banner('fruits-vegetables'),
  'gift stores': banner('gift-stores'),
  'groceries & provisions': banner('groceries-provisions'),
  'grocery & kirana': banner('grocery-kirana'),
  'hair care': banner('hair-care'),
  'hardware stores': banner('hardware-stores'),
  'health & personal care': banner('health-personal-care'),
  'home & kitchen': banner('home-kitchen'),
  'home services': banner('home-services'),
  'hospitals & clinics': banner('hospitals-clinics'),
  'hotels & stays': banner('hotels-stays'),
  'jewellery stores': banner('jewellery-stores'),
  'local manufacturers': banner('local-manufacturers'),
  'meat, fish & poultry': banner('meat-fish-poultry'),
  'medical stores & pharmacies': banner('medical-pharmacies'),
  'medicines & pharmacy': banner('medicines-pharmacy'),
  'mens clothing': banner('mens-clothing'),
  'milk, curd & butter': banner('milk-curd'),
  'mobile stores': banner('mobile-stores'),
  'mutton & goat': banner('mutton'),
  'perfumes & fragrances': banner('fragrances'),
  'pet stores & services': banner('pet-services'),
  'petrol stations': banner('petrol-pumps'),
  'pickles & papads': banner('pickles-papads'),
  'paneer & cheese': banner('paneer-cheese'),
  'plumbing services': banner('plumbing-services'),
  'printing & stationery': banner('printing-stationery'),
  'professional services': banner('professional-services'),
  'processed & frozen meat': banner('processed-meat'),
  'property services': banner('property-services'),
  'pulses & dals': banner('pulses-dals'),
  'ready to cook & instant': banner('ready-to-cook'),
  'repair services': banner('repair-services'),
  'rice & grains': banner('rice-grains'),
  'restaurants & food': banner('restaurants-food'),
  'salons & spas': banner('salons-spas'),
  schools: banner('schools'),
  'skin care': banner('skin-care'),
  'snacks & namkeen': banner('snacks-namkeen'),
  'spices & masalas': banner('spices-masalas'),
  'sports, fitness & outdoors': banner('sports-fitness-outdoors'),
  'sugar, salt & jaggery': banner('sugar-salt-jaggery'),
  'sweets & mithai': banner('sweets-mithai'),
  'tailoring & boutiques': banner('tailoring-services'),
  'tea, coffee & beverages': banner('tea-coffee-beverages'),
  'tiffin centres': banner('tiffin-centres-v2'),
  'toys, baby & kids': banner('toys-baby-kids'),
  'travel services': banner('travel-transport'),
  'tuition & coaching': banner('tuition-coaching'),
  'tyre & battery stores': banner('tyre-battery-stores'),
  'wholesale businesses': banner('wholesale-distribution'),
  'womens clothing': banner('womens-clothing'),
  'fresh vegetables': banner('fresh-vegetables'),
  'fresh fruits': banner('fresh-fruits'),
  'leafy greens & herbs': banner('leafy-greens'),
  'organic produce': banner('organic-produce'),
  'bath & body': banner('bath-body'),
  'oral care': banner('oral-care'),
  'health devices': banner('health-devices'),
  'supplements & nutrition': banner('supplements'),
  'sanitary & hygiene': banner('sanitary-hygiene'),
  makeup: banner('makeup'),
  grooming: banner('grooming'),
  'salon & spa products': banner('salon-supplies'),
  'clothing & footwear': banner('clothing-footwear'),
  'sarees & ethnic wear': banner('sarees-ethnic'),
  'kids clothing': banner('kids-clothing'),
  footwear: banner('footwear'),
  'bags & luggage': banner('bags-luggage'),
  'watches & accessories': banner('watches-accessories'),
  'jewellery & imitation': banner('jewellery'),
  'fabric & tailoring material': banner('fabric-tailoring'),
  'cookware & utensils': banner('cookware-utensils'),
  'storage & containers': banner('storage-containers'),
  'cleaning & detergents': banner('cleaning-supplies'),
  'home decor': banner('home-decor'),
  'bedding & curtains': banner('bedding-curtains'),
  'lighting & electricals': banner('lighting-electricals'),
  'gas stoves & cylinders': banner('gas-stoves'),
  'plastic & steelware': banner('plastic-steel-ware'),
  books: banner('books'),
  'school supplies': banner('school-supplies'),
  'office stationery': banner('office-stationery'),
  'art & craft': banner('art-craft'),
  'printing & xerox material': banner('printing-supplies'),
  'sports equipment': banner('sports-equipment'),
  'fitness & gym equipment': banner('fitness-gym'),
  'cycles & accessories': banner('cycles'),
  'outdoor & camping': banner('outdoor-camping'),
  'toys & games': banner('toys-games'),
  'baby gear': banner('baby-gear'),
  'baby food & diapers': banner('baby-food-diapers'),
  'pets & pet supplies': banner('pets-supplies'),
  'pet food': banner('pet-food'),
  'pet accessories': banner('pet-accessories'),
  'pets & livestock': banner('pets-livestock'),
  'farm, garden & agriculture': banner('farm-garden'),
  'seeds & saplings': banner('seeds-saplings'),
  'fertilizers & pesticides': banner('fertilizers-pesticides'),
  'farm tools & machinery': banner('farm-tools'),
  'plants & nursery': banner('plants-nursery'),
  'garden supplies': banner('garden-supplies'),
  'farm produce (bulk)': banner('farm-produce-bulk'),
  'hardware, tools & building': banner('hardware-tools'),
  'hand tools': banner('hand-tools'),
  'power tools': banner('power-tools'),
  'paints & finishes': banner('paints'),
  'plumbing & sanitary': banner('plumbing-sanitary'),
  'cement, steel & building materials': banner('building-materials'),
  'electrical supplies': banner('electrical-supplies'),
  'industrial & business supplies': banner('industrial-supplies'),
  'packaging material': banner('packaging'),
  'safety equipment': banner('safety-equipment'),
  'machinery & equipment': banner('machinery'),
  'hotel & restaurant supplies': banner('hotel-restaurant-supplies'),
  'raw materials': banner('raw-materials'),
  'musical instruments & hobby': banner('music-hobby'),
  'musical instruments': banner('musical-instruments'),
  'handicrafts & handmade': banner('handicrafts'),
  'collectibles & antiques': banner('collectibles'),
  'religious & festive': banner('religious-festive'),
  'pooja items': banner('pooja-items'),
  'festival decorations': banner('festival-decor'),
  'gifts & novelties': banner('gifts'),
  'agricultural supplies': banner('agricultural-supplies'),
  'other local businesses': banner('other-local-businesses'),
  electronics: banner('electronics'),
  'mobile phones': banner('mobile-phones'),
  'laptops & computers': banner('laptops-computers'),
  'tv & appliances': banner('tv-appliances'),
  vehicles: banner('vehicles'),
  cars: banner('cars'),
  'motorcycles & scooters': banner('motorcycles-scooters'),
  'furniture & home': banner('furniture-home'),
  jobs: banner('jobs'),
  'it & software': banner('jobs-it-software'),
  'sales & marketing': banner('jobs-sales-marketing'),
  'delivery & driver': banner('jobs-delivery-driver'),
  'retail & hospitality': banner('jobs-retail-hospitality'),
  services: banner('services'),
  'home repair': banner('services-home-repair'),
  'tuition & classes': banner('services-tuition'),
  'health & beauty': banner('services-health-beauty'),
  'real estate & rentals': banner('real-estate-rentals'),
  'local offers': banner('local-offers'),
  'salons & spa': banner('offers-salons-spa'),
  shopping: banner('offers-shopping'),
  businesses: banner('businesses'),
  restaurants: banner('business-restaurants'),
  'clinics & hospitals': banner('business-clinics'),
  'shops & retail': banner('business-shops'),
  events: banner('events'),
  // Business-name subtypes. Broad business categories remain the fallback; these keys
  // let storefront routing select a more precise banner when a business name or future
  // structured subtype clearly identifies the service being offered.
  'cafe-coffee': banner('cafe-coffee'),
  biryani: banner('biryani'),
  pizza: banner('pizza'),
  'fast-food': banner('fast-food'),
  'chinese-noodles': banner('chinese-noodles'),
  'ice-cream-desserts': banner('ice-cream-desserts'),
  'juice-shakes': banner('juice-shakes'),
  'tandoor-grill': banner('tandoor-grill'),
  'north-indian-thali': banner('north-indian-thali'),
  'south-indian-meals': banner('south-indian-meals'),
  'chaat-street-food': banner('chaat-street-food'),
  'dental-clinic': banner('dental-clinic'),
  'eye-clinic': banner('eye-clinic'),
  'skin-derma-clinic': banner('skin-derma-clinic'),
  'diagnostic-lab': banner('diagnostic-lab'),
  physiotherapy: banner('physiotherapy'),
  'veterinary-clinic': banner('veterinary-clinic'),
  'maternity-womens-clinic': banner('maternity-womens-clinic'),
  'multispeciality-hospital': banner('multispeciality-hospital'),
  'mens-salon-barber': banner('mens-salon-barber'),
  'womens-beauty-parlour': banner('womens-beauty-parlour'),
  'spa-massage': banner('spa-massage'),
  'nail-studio': banner('nail-studio'),
  'preschool-playschool': banner('preschool-playschool'),
  'coaching-competitive': banner('coaching-competitive'),
  'computer-training': banner('computer-training'),
  'music-dance-arts': banner('music-dance-arts'),
  'car-service-garage': banner('car-service-garage'),
  'car-wash': banner('car-wash'),
  'denting-painting': banner('denting-painting'),
  'auto-spare-parts': banner('auto-spare-parts'),
  'mobile-repair': banner('mobile-repair'),
  'mobile-accessories': banner('mobile-accessories'),
  'real-estate': banner('real-estate'),
  'hotel-lodge': banner('hotel-lodge'),
  'pg-hostel': banner('pg-hostel'),
  'travel-agency': banner('travel-agency'),
  'taxi-cab-rental': banner('taxi-cab-rental'),
  catering: banner('catering'),
  'event-decoration': banner('event-decoration'),
  'photography-studio': banner('photography-studio'),
  'tent-house-rental': banner('tent-house-rental'),
  'ac-appliance-repair': banner('ac-appliance-repair'),
  'deep-cleaning-pest': banner('deep-cleaning-pest'),
  'carpentry-woodwork': banner('carpentry-woodwork'),
  'painting-service': banner('painting-service'),
  'accounting-ca': banner('accounting-ca'),
  'legal-advocate': banner('legal-advocate'),
  'insurance-finance': banner('insurance-finance'),
  'architect-interior': banner('architect-interior'),
  'printing-press': banner('printing-press'),
  'flex-banner-signage': banner('flex-banner-signage'),
  'pet-grooming-clinic': banner('pet-grooming-clinic'),
  'aquarium-fish': banner('aquarium-fish'),
  'optical-store': banner('optical-store'),
  'sports-fitness-store': banner('sports-fitness-store'),
};

export function premiumCategoryBanner(name?: string | null): PremiumCategoryBanner | null {
  return name ? (categoryBanners[name.trim().toLowerCase()] ?? null) : null;
}

// A business only ever carries a broad category ("Restaurants & food"), so a dosa house, a café
// and a biryani spot would all show the same restaurant banner. When the business NAME clearly
// signals a sub-type we already have a dedicated banner for, use that instead — a dosa/tiffin place
// gets the breakfast banner, a café the coffee banner, a sweet shop the mithai banner. Scoped to the
// broad food categories so a "Coffee Table" furniture shop can never pick up a café banner, and
// ordered by specificity (first match wins) with word-boundary keywords to avoid misfires.
// Name-based sub-type banners, scoped BY business category so a keyword can only fire inside the
// category it belongs to — a "Coffee Table" furniture shop can never pick up a café banner, and
// "City Eye Hospital" only matches inside Hospitals. First match within the category wins; if none
// match (or the target banner is missing) it falls back to the plain category banner. Every `key`
// here is a registered entry in `categoryBanners`.
const SUBTYPE_OVERRIDES: Readonly<Record<string, ReadonlyArray<{ test: RegExp; key: string }>>> = {
  // "Other local businesses" is the import's catch-all — a badminton academy, a gym, a coaching
  // centre and a jeweller all land here, so the category banner is meaningless. This is where name
  // detection matters most: read the actual business type from the name and pick a fitting banner.
  // Ordered by specificity — a named sport wins over the generic "academy".
  'other local businesses': [
    {
      test: /\b(badminton|cricket|football|tennis|volleyball|basketball|skating|swimming|kabaddi|athletics?|sports?|turf|stadium|arena)\b/i,
      key: 'sports, fitness & outdoors',
    },
    {
      test: /\b(gym|fitness|yoga|crossfit|zumba|aerobics|workout)\b/i,
      key: 'fitness & gym equipment',
    },
    {
      test: /\b(coaching|tuition|institute|classes|academy|iit|neet|upsc)\b/i,
      key: 'coaching-competitive',
    },
    { test: /\b(computers?|software)\b/i, key: 'computer-training' },
    { test: /\b(music|dance|karate|drawing|abacus)\b/i, key: 'music-dance-arts' },
    { test: /\b(dental|dentist)\b/i, key: 'dental-clinic' },
    { test: /\b(clinic|hospital|nursing home|diagnostic|scan)\b/i, key: 'hospitals & clinics' },
    { test: /\b(pharmacy|medical|medicals|chemist)\b/i, key: 'medical stores & pharmacies' },
    { test: /\b(salons?|parlou?r|beauty|spa)\b/i, key: 'salons & spas' },
    { test: /\b(travels?|tours?|holidays?)\b/i, key: 'travel-agency' },
    { test: /\b(caterers?|catering)\b/i, key: 'catering' },
    { test: /\b(photo\w*|studio)\b/i, key: 'photography-studio' },
    { test: /\b(real ?estate|properties|builders?|realtor)\b/i, key: 'real-estate' },
    { test: /\b(mobiles?|cellphones?)\b/i, key: 'mobile stores' },
    { test: /\b(jewell?ers?|jewell?ery)\b/i, key: 'jewellery stores' },
    { test: /\b(furnitures?)\b/i, key: 'furniture stores' },
    { test: /\b(hardware|electricals?)\b/i, key: 'hardware stores' },
    { test: /\b(hotels?|lodge|restaurants?|biryani|tiffin|dhaba)\b/i, key: 'restaurants & food' },
    { test: /\b(cafe|café|coffee)\b/i, key: 'cafe-coffee' },
    { test: /\b(bakery|bakers|cakes?)\b/i, key: 'cakes & pastries' },
    { test: /\b(sweets?|mithai)\b/i, key: 'sweets & mithai' },
  ],
  'restaurants & food': [
    { test: /\b(dosas?|tiffins?|idlis?|vadas?|udupi|breakfast)\b/i, key: 'tiffin centres' },
    { test: /\b(biryani|biriyani|dum)\b/i, key: 'biryani' },
    { test: /\b(pizza|pizzeria)\b/i, key: 'pizza' },
    { test: /\b(kfc|fried chicken|burgers?|fast ?food)\b/i, key: 'fast-food' },
    { test: /\b(chinese|noodles?|manchurian|hakka|momos?)\b/i, key: 'chinese-noodles' },
    { test: /\b(ice ?cream|gelato|kulfi|falooda|desserts?)\b/i, key: 'ice-cream-desserts' },
    { test: /\b(juices?|smoothies?|shakes?|milkshake)\b/i, key: 'juice-shakes' },
    { test: /\b(tandoor\w*|kebabs?|grill|bbq|barbeque|barbecue)\b/i, key: 'tandoor-grill' },
    { test: /\b(chaat|pani ?puri|bhel|street ?food)\b/i, key: 'chaat-street-food' },
    { test: /\b(sweets?|mithai|misthan|mishtan)\b/i, key: 'sweets & mithai' },
    { test: /\b(bakery|bakers|cakes?|pastr\w*)\b/i, key: 'cakes & pastries' },
    { test: /\b(cafe|café|coffee|barista|brew)\b/i, key: 'cafe-coffee' },
    { test: /\b(thali|punjabi|north ?indian)\b/i, key: 'north-indian-thali' },
    { test: /\b(meals|andhra|south ?indian)\b/i, key: 'south-indian-meals' },
  ],
  'hospitals & clinics': [
    { test: /\b(dental|dentist|teeth|orthodont\w*)/i, key: 'dental-clinic' },
    { test: /\b(eye|vision|optical|opthal\w*|ophthal\w*|netra)\b/i, key: 'eye-clinic' },
    { test: /\b(skin|derma\w*|cosmetolog\w*)\b/i, key: 'skin-derma-clinic' },
    {
      test: /\b(diagnostics?|labs?|laborator\w*|scans?|pathology|imaging|x-?ray)\b/i,
      key: 'diagnostic-lab',
    },
    { test: /\bphysio\w*/i, key: 'physiotherapy' },
    { test: /\b(veterinary|vet|animal)\b/i, key: 'veterinary-clinic' },
    {
      test: /\b(maternity|gyna?ec\w*|fertility|ivf|nursing home)\b/i,
      key: 'maternity-womens-clinic',
    },
    {
      test: /\b(multi ?speciality|multi ?specialty|general hospital)\b/i,
      key: 'multispeciality-hospital',
    },
  ],
  'salons & spas': [
    { test: /\b(barbers?|gents?|mens?|hair ?cutting)\b/i, key: 'mens-salon-barber' },
    {
      test: /\b(beauty ?parlou?r|ladies|womens?|bridal|makeover)\b/i,
      key: 'womens-beauty-parlour',
    },
    { test: /\b(spa|massage|ayurved\w*)\b/i, key: 'spa-massage' },
    { test: /\bnails?\b/i, key: 'nail-studio' },
  ],
  'beauty & wellness': [
    { test: /\b(spa|massage)\b/i, key: 'spa-massage' },
    { test: /\bnails?\b/i, key: 'nail-studio' },
  ],
  'tuition & coaching': [
    { test: /\b(iit|neet|eamcet|upsc|ias|coaching|academy)\b/i, key: 'coaching-competitive' },
    { test: /\b(computers?|software|typing)\b/i, key: 'computer-training' },
    { test: /\b(music|dance|abacus|arts?|drawing|karate)\b/i, key: 'music-dance-arts' },
  ],
  'education & training': [
    { test: /\b(iit|neet|upsc|coaching|academy)\b/i, key: 'coaching-competitive' },
    { test: /\b(computers?|software)\b/i, key: 'computer-training' },
    { test: /\b(music|dance|arts?|abacus)\b/i, key: 'music-dance-arts' },
  ],
  schools: [
    {
      test: /\b(pre ?school|play ?school|kinder\w*|montessori|nursery)\b/i,
      key: 'preschool-playschool',
    },
  ],
  'automobile services': [
    { test: /\b(wash|detailing)\b/i, key: 'car-wash' },
    { test: /\b(denting|painting|body ?shop)\b/i, key: 'denting-painting' },
    { test: /\b(spare ?parts?|spares|accessories)\b/i, key: 'auto-spare-parts' },
    { test: /\b(service|garage|motors|workshop)\b/i, key: 'car-service-garage' },
  ],
  'mobile stores': [
    { test: /\b(repairs?|service)\b/i, key: 'mobile-repair' },
    { test: /\b(accessories|covers?|cases?)\b/i, key: 'mobile-accessories' },
  ],
  'property services': [
    { test: /\b(real ?estate|propert\w*|realtor|builders?|estates?)\b/i, key: 'real-estate' },
  ],
  'hotels & stays': [{ test: /\b(pg|hostel|paying ?guest)\b/i, key: 'pg-hostel' }],
  'travel services': [
    { test: /\b(taxi|cabs?|car ?rental|travels)\b/i, key: 'taxi-cab-rental' },
    { test: /\b(travels?|tours?|holidays?|tourism)\b/i, key: 'travel-agency' },
  ],
  'event services': [
    { test: /\b(catering|caterers?)\b/i, key: 'catering' },
    { test: /\b(decor\w*|florist|flowers?)\b/i, key: 'event-decoration' },
    { test: /\b(photo\w*|studio|videograph\w*)\b/i, key: 'photography-studio' },
    { test: /\b(tent|mandap|function ?hall)\b/i, key: 'tent-house-rental' },
  ],
  'home services': [
    {
      test: /\b(ac|air ?con\w*|appliance|refrigerat\w*|washing ?machine)\b/i,
      key: 'ac-appliance-repair',
    },
    { test: /\b(carpent\w*|woodwork|furniture)\b/i, key: 'carpentry-woodwork' },
    { test: /\b(painting|painters?)\b/i, key: 'painting-service' },
    { test: /\b(cleaning|pest ?control)\b/i, key: 'deep-cleaning-pest' },
  ],
  'cleaning services': [
    { test: /\b(pest ?control|deep ?cleaning|cleaning)\b/i, key: 'deep-cleaning-pest' },
  ],
  'professional services': [
    {
      test: /\b(chartered ?accountant|accounting|accounts?|tax|\bca\b|audit\w*)\b/i,
      key: 'accounting-ca',
    },
    { test: /\b(advocate|lawyer|legal|law\b)\b/i, key: 'legal-advocate' },
    { test: /\b(insurance|finance|loans?|investment\w*)\b/i, key: 'insurance-finance' },
    { test: /\b(architect\w*|interior\w*|design\w*)\b/i, key: 'architect-interior' },
  ],
  'printing & stationery': [
    { test: /\b(flex|banners?|signage|vinyl|hoarding)\b/i, key: 'flex-banner-signage' },
    { test: /\b(printing|printers?|press|xerox|offset)\b/i, key: 'printing-press' },
  ],
  'pet stores & services': [
    { test: /\b(grooming|clinic|vet)\b/i, key: 'pet-grooming-clinic' },
    { test: /\b(aquarium|fish|aquatic)\b/i, key: 'aquarium-fish' },
  ],
  'clothing stores': [
    { test: /\b(sarees?|saris?|ethnic|silks?)\b/i, key: 'sarees & ethnic wear' },
    { test: /\b(kids|childrens?|baby)\b/i, key: 'kids clothing' },
    { test: /\b(footwear|shoes?|chappals?|sandals?)\b/i, key: 'footwear' },
    { test: /\b(ladies|womens?)\b/i, key: 'womens clothing' },
    { test: /\b(gents?|mens?)\b/i, key: 'mens clothing' },
  ],
  'jewellery stores': [
    { test: /\b(imitation|artificial|fashion)\b/i, key: 'jewellery & imitation' },
  ],
};

/**
 * The banner for a specific business: a name-based sub-type refinement over the plain category
 * banner, scoped to the business's category so it can never misfire across categories. Falls back
 * to the category banner (then the monogram) when the name says nothing specific — so it never
 * shows a worse banner than before, only a more fitting one.
 */
export function premiumBusinessBanner(
  name?: string | null,
  categoryName?: string | null,
): PremiumCategoryBanner | null {
  const category = categoryName?.trim().toLowerCase();
  const overrides = category ? SUBTYPE_OVERRIDES[category] : undefined;
  if (name && overrides) {
    for (const { test, key } of overrides) {
      if (test.test(name) && categoryBanners[key]) return categoryBanners[key]!;
    }
  }
  return premiumCategoryBanner(categoryName);
}
