export type PremiumCategoryBanner = Readonly<{
  desktop: string;
  mobile: string;
}>;

function banner(slug: string): PremiumCategoryBanner {
  return {
    desktop: `/banners/categories/${slug}-desktop.webp`,
    mobile: `/banners/categories/${slug}-mobile.webp`,
  };
}

const automobile = banner('automobile-services-v2');
const beauty = banner('beauty-wellness-v2');
const education = banner('education-training');

const categoryBanners: Readonly<Record<string, PremiumCategoryBanner>> = {
  'automobile services': automobile,
  'ayurveda & herbal': banner('ayurveda-herbal'),
  'bakeries & sweets': banner('bakeries-sweets-v5'),
  'bread & buns': banner('bread-buns'),
  'beauty & cosmetics': banner('beauty-cosmetics'),
  'beauty & wellness': beauty,
  'bike repair': banner('bike-repair'),
  'books, stationery & office': banner('books-stationery'),
  'cakes & pastries': banner('cakes-pastries'),
  'car repair': banner('car-repair'),
  chicken: banner('chicken'),
  'cleaning services': banner('cleaning-services'),
  'clothing stores': banner('clothing-stores'),
  colleges: banner('colleges'),
  'computer & laptop stores': banner('computer-laptop-stores'),
  'cooking oil & ghee': banner('cooking-oil-ghee'),
  'courier & parcel': banner('courier-parcel'),
  'dairy, bakery & eggs': banner('dairy-bakery-eggs'),
  'dry fruits & nuts': banner('dry-fruits-nuts'),
  eggs: banner('eggs'),
  'education & training': education,
  'electrical services': banner('electrical-services'),
  'electrical stores': banner('electrical-stores'),
  'electronics stores': banner('electronics-stores'),
  'event services': banner('event-services'),
  'ev charging stations': banner('ev-charging-stations'),
  'flour & atta': banner('flour-atta'),
  'fish & seafood': banner('fish-seafood'),
  'footwear stores': banner('footwear-stores'),
  'furniture stores': banner('furniture-stores'),
  'fruits & vegetables': banner('fruits-vegetables'),
  'gift stores': banner('gift-stores'),
  'groceries & provisions': banner('groceries-provisions'),
  'grocery & kirana': banner('grocery-kirana'),
  'hair care': banner('hair-care'),
  'hardware stores': banner('hardware-stores'),
  'health & personal care': banner('health-personal-care'),
  'home & kitchen': banner('home-kitchen'),
  'home services': banner('home-services'),
  'hospitals & clinics': banner('hospitals-clinics'),
  'hotels & stays': banner('hotels-stays'),
  'jewellery stores': banner('jewellery-stores'),
  'local manufacturers': banner('local-manufacturers'),
  'meat, fish & poultry': banner('meat-fish-poultry'),
  'medical stores & pharmacies': banner('medical-pharmacies'),
  'medicines & pharmacy': banner('medicines-pharmacy'),
  'mens clothing': banner('mens-clothing'),
  'milk, curd & butter': banner('milk-curd'),
  'mobile stores': banner('mobile-stores'),
  'mutton & goat': banner('mutton'),
  'perfumes & fragrances': banner('fragrances'),
  'pet stores & services': banner('pet-services'),
  'petrol stations': banner('petrol-pumps'),
  'pickles & papads': banner('pickles-papads'),
  'paneer & cheese': banner('paneer-cheese'),
  'plumbing services': banner('plumbing-services'),
  'printing & stationery': banner('printing-stationery'),
  'professional services': banner('professional-services'),
  'processed & frozen meat': banner('processed-meat'),
  'property services': banner('property-services'),
  'pulses & dals': banner('pulses-dals'),
  'ready to cook & instant': banner('ready-to-cook'),
  'repair services': banner('repair-services'),
  'rice & grains': banner('rice-grains'),
  'restaurants & food': banner('restaurants-food'),
  'salons & spas': banner('salons-spas'),
  schools: banner('schools'),
  'skin care': banner('skin-care'),
  'snacks & namkeen': banner('snacks-namkeen'),
  'spices & masalas': banner('spices-masalas'),
  'sports, fitness & outdoors': banner('sports-fitness-outdoors'),
  'sugar, salt & jaggery': banner('sugar-salt-jaggery'),
  'sweets & mithai': banner('sweets-mithai'),
  'tailoring & boutiques': banner('tailoring-services'),
  'tea, coffee & beverages': banner('tea-coffee-beverages'),
  'tiffin centres': banner('tiffin-centres-v2'),
  'toys, baby & kids': banner('toys-baby-kids'),
  'travel services': banner('travel-transport'),
  'tuition & coaching': banner('tuition-coaching'),
  'tyre & battery stores': banner('tyre-battery-stores'),
  'wholesale businesses': banner('wholesale-distribution'),
  'womens clothing': banner('womens-clothing'),
  'fresh vegetables': banner('fresh-vegetables'),
  'fresh fruits': banner('fresh-fruits'),
  'leafy greens & herbs': banner('leafy-greens'),
  'organic produce': banner('organic-produce'),
  'bath & body': banner('bath-body'),
  'oral care': banner('oral-care'),
  'health devices': banner('health-devices'),
  'supplements & nutrition': banner('supplements'),
  'sanitary & hygiene': banner('sanitary-hygiene'),
  makeup: banner('makeup'),
  grooming: banner('grooming'),
  'salon & spa products': banner('salon-supplies'),
  'clothing & footwear': banner('clothing-footwear'),
  'sarees & ethnic wear': banner('sarees-ethnic'),
  'kids clothing': banner('kids-clothing'),
  footwear: banner('footwear'),
  'bags & luggage': banner('bags-luggage'),
  'watches & accessories': banner('watches-accessories'),
  'jewellery & imitation': banner('jewellery'),
  'fabric & tailoring material': banner('fabric-tailoring'),
  'cookware & utensils': banner('cookware-utensils'),
  'storage & containers': banner('storage-containers'),
  'cleaning & detergents': banner('cleaning-supplies'),
  'home decor': banner('home-decor'),
  'bedding & curtains': banner('bedding-curtains'),
  'lighting & electricals': banner('lighting-electricals'),
  'gas stoves & cylinders': banner('gas-stoves'),
  'plastic & steelware': banner('plastic-steel-ware'),
  books: banner('books'),
  'school supplies': banner('school-supplies'),
  'office stationery': banner('office-stationery'),
  'art & craft': banner('art-craft'),
  'printing & xerox material': banner('printing-supplies'),
  'sports equipment': banner('sports-equipment'),
  'fitness & gym equipment': banner('fitness-gym'),
  'cycles & accessories': banner('cycles'),
  'outdoor & camping': banner('outdoor-camping'),
  'toys & games': banner('toys-games'),
  'baby gear': banner('baby-gear'),
  'baby food & diapers': banner('baby-food-diapers'),
  'pets & pet supplies': banner('pets-supplies'),
  'pet food': banner('pet-food'),
  'pet accessories': banner('pet-accessories'),
  'pets & livestock': banner('pets-livestock'),
  'farm, garden & agriculture': banner('farm-garden'),
  'seeds & saplings': banner('seeds-saplings'),
  'fertilizers & pesticides': banner('fertilizers-pesticides'),
  'farm tools & machinery': banner('farm-tools'),
  'plants & nursery': banner('plants-nursery'),
  'garden supplies': banner('garden-supplies'),
  'farm produce (bulk)': banner('farm-produce-bulk'),
  'hardware, tools & building': banner('hardware-tools'),
  'hand tools': banner('hand-tools'),
  'power tools': banner('power-tools'),
  'paints & finishes': banner('paints'),
  'plumbing & sanitary': banner('plumbing-sanitary'),
  'cement, steel & building materials': banner('building-materials'),
  'electrical supplies': banner('electrical-supplies'),
  'industrial & business supplies': banner('industrial-supplies'),
  'packaging material': banner('packaging'),
  'safety equipment': banner('safety-equipment'),
  'machinery & equipment': banner('machinery'),
  'hotel & restaurant supplies': banner('hotel-restaurant-supplies'),
  'raw materials': banner('raw-materials'),
  'musical instruments & hobby': banner('music-hobby'),
  'musical instruments': banner('musical-instruments'),
  'handicrafts & handmade': banner('handicrafts'),
  'collectibles & antiques': banner('collectibles'),
  'religious & festive': banner('religious-festive'),
  'pooja items': banner('pooja-items'),
  'festival decorations': banner('festival-decor'),
  'gifts & novelties': banner('gifts'),
  'agricultural supplies': banner('agricultural-supplies'),
  'other local businesses': banner('other-local-businesses'),
  electronics: banner('electronics'),
  'mobile phones': banner('mobile-phones'),
  'laptops & computers': banner('laptops-computers'),
  'tv & appliances': banner('tv-appliances'),
  vehicles: banner('vehicles'),
  cars: banner('cars'),
  'motorcycles & scooters': banner('motorcycles-scooters'),
  'furniture & home': banner('furniture-home'),
  jobs: banner('jobs'),
  'it & software': banner('jobs-it-software'),
  'sales & marketing': banner('jobs-sales-marketing'),
  'delivery & driver': banner('jobs-delivery-driver'),
  'retail & hospitality': banner('jobs-retail-hospitality'),
  services: banner('services'),
  'home repair': banner('services-home-repair'),
  'tuition & classes': banner('services-tuition'),
  'health & beauty': banner('services-health-beauty'),
  'real estate & rentals': banner('real-estate-rentals'),
  'local offers': banner('local-offers'),
  'salons & spa': banner('offers-salons-spa'),
  shopping: banner('offers-shopping'),
  businesses: banner('businesses'),
  restaurants: banner('business-restaurants'),
  'clinics & hospitals': banner('business-clinics'),
  'shops & retail': banner('business-shops'),
  events: banner('events'),
  // Business-name subtypes. Broad business categories remain the fallback; these keys
  // let storefront routing select a more precise banner when a business name or future
  // structured subtype clearly identifies the service being offered.
  'cafe-coffee': banner('cafe-coffee'),
  biryani: banner('biryani'),
  pizza: banner('pizza'),
  'fast-food': banner('fast-food'),
  'chinese-noodles': banner('chinese-noodles'),
  'ice-cream-desserts': banner('ice-cream-desserts'),
  'juice-shakes': banner('juice-shakes'),
  'tandoor-grill': banner('tandoor-grill'),
  'north-indian-thali': banner('north-indian-thali'),
  'south-indian-meals': banner('south-indian-meals'),
  'chaat-street-food': banner('chaat-street-food'),
  'dental-clinic': banner('dental-clinic'),
  'eye-clinic': banner('eye-clinic'),
  'skin-derma-clinic': banner('skin-derma-clinic'),
  'diagnostic-lab': banner('diagnostic-lab'),
  physiotherapy: banner('physiotherapy'),
  'veterinary-clinic': banner('veterinary-clinic'),
  'maternity-womens-clinic': banner('maternity-womens-clinic'),
  'multispeciality-hospital': banner('multispeciality-hospital'),
  'mens-salon-barber': banner('mens-salon-barber'),
  'womens-beauty-parlour': banner('womens-beauty-parlour'),
  'spa-massage': banner('spa-massage'),
  'nail-studio': banner('nail-studio'),
  'preschool-playschool': banner('preschool-playschool'),
  'coaching-competitive': banner('coaching-competitive'),
  'computer-training': banner('computer-training'),
  'music-dance-arts': banner('music-dance-arts'),
  'car-service-garage': banner('car-service-garage'),
  'car-wash': banner('car-wash'),
  'denting-painting': banner('denting-painting'),
  'auto-spare-parts': banner('auto-spare-parts'),
  'mobile-repair': banner('mobile-repair'),
  'mobile-accessories': banner('mobile-accessories'),
  'real-estate': banner('real-estate'),
  'hotel-lodge': banner('hotel-lodge'),
  'pg-hostel': banner('pg-hostel'),
  'travel-agency': banner('travel-agency'),
  'taxi-cab-rental': banner('taxi-cab-rental'),
  catering: banner('catering'),
  'event-decoration': banner('event-decoration'),
  'photography-studio': banner('photography-studio'),
  'tent-house-rental': banner('tent-house-rental'),
  'ac-appliance-repair': banner('ac-appliance-repair'),
  'deep-cleaning-pest': banner('deep-cleaning-pest'),
  'carpentry-woodwork': banner('carpentry-woodwork'),
  'painting-service': banner('painting-service'),
  'accounting-ca': banner('accounting-ca'),
  'legal-advocate': banner('legal-advocate'),
  'insurance-finance': banner('insurance-finance'),
  'architect-interior': banner('architect-interior'),
  'printing-press': banner('printing-press'),
  'flex-banner-signage': banner('flex-banner-signage'),
  'pet-grooming-clinic': banner('pet-grooming-clinic'),
  'aquarium-fish': banner('aquarium-fish'),
  'optical-store': banner('optical-store'),
  'sports-fitness-store': banner('sports-fitness-store'),
  'schools & colleges': banner('schools-colleges'),
  'petrol pumps': banner('petrol-pumps'),
  'bakeries & sweet shops': banner('bakeries-sweet-shops'),
  'tutoring centres & coaching classes': banner('tutoring-centres-coaching-classes'),
  'car repair & servicing workshops': banner('car-repair-servicing-workshops'),
  'shoe stores & footwear shops': banner('shoe-stores-footwear-shops'),
  'religious organizations': banner('religious-organizations'),
  'arts & entertainment': banner('arts-entertainment'),
  'diagnostic imaging centres': banner('diagnostic-imaging-centres'),
  'book shops': banner('book-shops'),
  'coffee shops': banner('coffee-shops'),
  'dental clinics': banner('dental-clinics'),
  'private schools': banner('private-schools'),
  'special schools': banner('special-schools'),
  farms: banner('farms'),
  'public schools': banner('public-schools'),
  'candy shops': banner('candy-shops'),
  'chemical plants': banner('chemical-plants'),
  'auto detailers': banner('auto-detailers'),
  'b2b energy services': banner('b2b-energy-services'),
  'plant nurseries': banner('plant-nurseries'),
  'hardware companies': banner('hardware-companies'),
  'middle schools': banner('middle-schools'),
  'health food stores': banner('health-food-stores'),
  'stadium arenas': banner('stadium-arenas'),
  'barber shops': banner('barber-shops'),
  'surgery hospitals': banner('surgery-hospitals'),
  'music production studios': banner('music-production-studios'),
  'camping grounds': banner('camping-grounds'),
  'glass and mirror shops': banner('glass-and-mirror-shops'),
  'pet care services': banner('pet-care-services'),
  'vitamin shops': banner('vitamin-shops'),
  'food distributors': banner('food-distributors'),
  'audio visual shops': banner('audio-visual-shops'),
  'family practice clinics': banner('family-practice-clinics'),
  'lingerie shops': banner('lingerie-shops'),
  'e commerce services': banner('e-commerce-services'),
  'shipping centres': banner('shipping-centres'),
  'plastics manufacturers': banner('plastics-manufacturers'),
  'designer wear shops': banner('designer-wear-shops'),
  'urology clinics': banner('urology-clinics'),
  'countertop installers': banner('countertop-installers'),
  'amusement parks': banner('amusement-parks'),
  'fertility clinics': banner('fertility-clinics'),
  'tobacco shops': banner('tobacco-shops'),
  'banks & atms': banner('banks-atms'),
  'medical shops': banner('medical-shops'),
  'historic places': banner('historic-places'),
  'preschools & play schools': banner('preschools-play-schools'),
  'local manufacturers & producers': banner('local-manufacturers-producers'),
  'government & public services': banner('government-public-services'),
  'building contractors': banner('building-contractors'),
  'medical supply shops': banner('medical-supply-shops'),
  'pizza restaurants': banner('pizza-restaurants'),
  'lab testing centres': banner('lab-testing-centres'),
  'real estate agents': banner('real-estate-agents'),
  'marketing agencies': banner('marketing-agencies'),
  'movie theatres': banner('movie-theatres'),
  'engineering services': banner('engineering-services'),
  'malls & department stores': banner('malls-department-stores'),
  'tea rooms': banner('tea-rooms'),
  'music venues': banner('music-venues'),
  'convenience stores': banner('convenience-stores'),
  'chinese restaurants': banner('chinese-restaurants'),
  'research institutes': banner('research-institutes'),
  'home cleaners': banner('home-cleaners'),
  'graphic designers': banner('graphic-designers'),
  'art galleries': banner('art-galleries'),
  'electronic parts suppliers': banner('electronic-parts-suppliers'),
  'internet marketing services': banner('internet-marketing-services'),
  'law firms & advocates': banner('law-firms-advocates'),
  'surgical equipment suppliers': banner('surgical-equipment-suppliers'),
  'pest control services': banner('pest-control-services'),
  'electrician services': banner('electrician-services'),
  'mattress shops': banner('mattress-shops'),
  'media production houses': banner('media-production-houses'),
  'car manufacturers': banner('car-manufacturers'),
  'holiday rental homes': banner('holiday-rental-homes'),
  'camera and photo studios': banner('camera-and-photo-studios'),
  'meat shops': banner('meat-shops'),
  'appliance manufacturers': banner('appliance-manufacturers'),
  'pubs and bars': banner('pubs-and-bars'),
  'auto customization shops': banner('auto-customization-shops'),
  'arts & culture': banner('arts-culture'),
  'courts & tribunals': banner('courts-tribunals'),
  'commercial vehicle dealers': banner('commercial-vehicle-dealers'),
  'wholesale grocers': banner('wholesale-grocers'),
  'oncology clinics': banner('oncology-clinics'),
  'electric utility providers': banner('electric-utility-providers'),
  'cupcake shops': banner('cupcake-shops'),
  'indian restaurants': banner('indian-restaurants'),
  'credit unions & cooperative banks': banner('credit-unions-cooperative-banks'),
  'women clothing & ethnic wear shops': banner('women-clothing-ethnic-wear-shops'),
  'two-wheeler showrooms & dealers': banner('two-wheeler-showrooms-dealers'),
  'spas & wellness centres': banner('spas-wellness-centres'),
  'it companies': banner('it-companies'),
  'home developers': banner('home-developers'),
  'stock brokers': banner('stock-brokers'),
  'fashion boutiques': banner('fashion-boutiques'),
  'public parks': banner('public-parks'),
  'ad agencies': banner('ad-agencies'),
  'bars and pubs': banner('bars-and-pubs'),
  'tyre dealers': banner('tyre-dealers'),
  'building material shops': banner('building-material-shops'),
  'law firms': banner('law-firms'),
  'web designers': banner('web-designers'),
  'fashion accessories shops': banner('fashion-accessories-shops'),
  'language schools': banner('language-schools'),
  'makeup artists': banner('makeup-artists'),
  'telecom companies': banner('telecom-companies'),
  'financial advisors': banner('financial-advisors'),
  'carpet stores': banner('carpet-stores'),
  'driving schools': banner('driving-schools'),
  'finance & insurance': banner('finance-insurance'),
  'asian restaurants': banner('asian-restaurants'),
  'appliance repair services': banner('appliance-repair-services'),
  'used car dealers': banner('used-car-dealers'),
  'ac and cooling services': banner('ac-and-cooling-services'),
  'skin care salons': banner('skin-care-salons'),
  'guest houses': banner('guest-houses'),
  'home security services': banner('home-security-services'),
  'medical colleges': banner('medical-colleges'),
  'sign makers': banner('sign-makers'),
  'ent specialists': banner('ent-specialists'),
  'plastic surgery centres': banner('plastic-surgery-centres'),
  'flight training schools': banner('flight-training-schools'),
  'tile stores': banner('tile-stores'),
  brokers: banner('brokers'),
  'solar panel installers': banner('solar-panel-installers'),
  chocolatiers: banner('chocolatiers'),
  'breakfast and brunch restaurants': banner('breakfast-and-brunch-restaurants'),
  airports: banner('airports'),
  'service apartments': banner('service-apartments'),
  'specialty food stores': banner('specialty-food-stores'),
  'event planners': banner('event-planners'),
  'beauty salons': banner('beauty-salons'),
  'hardware & building material shops': banner('hardware-building-material-shops'),
  'auto parts & spare parts shops': banner('auto-parts-spare-parts-shops'),
  'fast food & quick bite restaurants': banner('fast-food-quick-bite-restaurants'),
  'places of worship': banner('places-of-worship'),
  'computer shops': banner('computer-shops'),
  'flowers & gift shops': banner('flowers-gift-shops'),
  'lodging services': banner('lodging-services'),
  'tour operators': banner('tour-operators'),
  'dessert shops': banner('dessert-shops'),
  'gas suppliers': banner('gas-suppliers'),
  'test prep centres': banner('test-prep-centres'),
  mosques: banner('mosques'),
  accountants: banner('accountants'),
  'auto companies': banner('auto-companies'),
  'b2b marketing agencies': banner('b2b-marketing-agencies'),
  'day care preschools': banner('day-care-preschools'),
  'childrens clothing stores': banner('childrens-clothing-stores'),
  'school campus buildings': banner('school-campus-buildings'),
  'paint stores': banner('paint-stores'),
  'employment agencies': banner('employment-agencies'),
  'eye care clinics': banner('eye-care-clinics'),
  'food stalls & eateries': banner('food-stalls-eateries'),
  'optometry clinics': banner('optometry-clinics'),
  'social media agencies': banner('social-media-agencies'),
  'auditorium venues': banner('auditorium-venues'),
  'sports and recreation': banner('sports-and-recreation'),
  'sports facilities': banner('sports-facilities'),
  'film studios': banner('film-studios'),
  'medical service centres': banner('medical-service-centres'),
  'bed and breakfasts': banner('bed-and-breakfasts'),
  'stationery shops': banner('stationery-shops'),
  'cottage stays': banner('cottage-stays'),
  'musical instrument shops': banner('musical-instrument-shops'),
  'patisserie cake shops': banner('patisserie-cake-shops'),
  'massage therapy centres': banner('massage-therapy-centres'),
  'commercial real estate': banner('commercial-real-estate'),
  'italian restaurants': banner('italian-restaurants'),
  'storage warehouses': banner('storage-warehouses'),
  'beauty training institutes': banner('beauty-training-institutes'),
  "women's care centres": banner('womens-care-centres'),
  'aquatic pet shops': banner('aquatic-pet-shops'),
  'bottled water companies': banner('bottled-water-companies'),
  carpenters: banner('carpenters'),
  'education centres': banner('education-centres'),
  'auto dealers': banner('auto-dealers'),
  'cafes & coffee shops': banner('cafes-and-coffee-shops'),
  'dental clinics & tooth care centres': banner('dental-clinics-and-tooth-care-centres'),
  'primary schools & elementary schools': banner('primary-schools-and-elementary-schools'),
  "men's clothing shops": banner('mens-clothing-shops'),
  'printing services': banner('printing-services'),
  'shopping malls': banner('shopping-malls'),
  'naturopathy centres': banner('naturopathy-centres'),
  'hair salons': banner('hair-salons'),
  'agri service providers': banner('agri-service-providers'),
  'jewellery makers': banner('jewellery-makers'),
  'hardware shops': banner('hardware-shops'),
  'appliance shops': banner('appliance-shops'),
  'telecom services': banner('telecom-services'),
  'ngo associations': banner('ngo-associations'),
  caterers: banner('caterers'),
  'pharmaceutical companies': banner('pharmaceutical-companies'),
  'vegetarian restaurants': banner('vegetarian-restaurants'),
  'corporate offices': banner('corporate-offices'),
  'wedding planners': banner('wedding-planners'),
  'loan providers': banner('loan-providers'),
  'plastic manufacturers': banner('plastic-manufacturers'),
  'clothing companies': banner('clothing-companies'),
  'bridal shops': banner('bridal-shops'),
  lounges: banner('lounges'),
  'passport services': banner('passport-services'),
  'machine shops': banner('machine-shops'),
  'charity organisations': banner('charity-organisations'),
  'bar and grill restaurants': banner('bar-and-grill-restaurants'),
  'nursing schools': banner('nursing-schools'),
  'power companies': banner('power-companies'),
  'investment advisors': banner('investment-advisors'),
  'medical research institutes': banner('medical-research-institutes'),
  'motorsport vehicle dealers': banner('motorsport-vehicle-dealers'),
  'seafood restaurants': banner('seafood-restaurants'),
  'home health care': banner('home-health-care'),
  'cricket ground rentals': banner('cricket-ground-rentals'),
  'tractor dealers': banner('tractor-dealers'),
  'blood donation centres': banner('blood-donation-centres'),
  'performing arts venues': banner('performing-arts-venues'),
  'dance clubs': banner('dance-clubs'),
  'watch shops': banner('watch-shops'),
  'student unions': banner('student-unions'),
  'hair supply stores': banner('hair-supply-stores'),
  'financial services': banner('financial-services'),
  'resorts & stays': banner('resorts-stays'),
  'health care centres & clinics': banner('health-care-centres-clinics'),
  'high schools & secondary schools': banner('high-schools-secondary-schools'),
  'software development companies': banner('software-development-companies'),
  'computer coaching classes': banner('computer-coaching-classes'),
  'property managers': banner('property-managers'),
  'student hostels': banner('student-hostels'),
  'outpatient clinics': banner('outpatient-clinics'),
  'eyewear shops': banner('eyewear-shops'),
  'police stations': banner('police-stations'),
  'construction & contractors': banner('construction-contractors'),
  'apparel stores': banner('apparel-stores'),
  'indian grocery shops': banner('indian-grocery-shops'),
  'textile manufacturers': banner('textile-manufacturers'),
  'diagnostic labs & imaging': banner('diagnostic-labs-imaging'),
  'budget lodges': banner('budget-lodges'),
  'tyre shops': banner('tyre-shops'),
  'gynecology clinics': banner('gynecology-clinics'),
  'agriculture suppliers': banner('agriculture-suppliers'),
  'orthopedic clinics': banner('orthopedic-clinics'),
  'music schools': banner('music-schools'),
  'electronic equipment suppliers': banner('electronic-equipment-suppliers'),
  'car wash services': banner('car-wash-services'),
  "children's clinics": banner('children-s-clinics'),
  'marketing consultants': banner('marketing-consultants'),
  'veterinary clinics': banner('veterinary-clinics'),
  'organic grocery stores': banner('organic-grocery-stores'),
  'truck dealers': banner('truck-dealers'),
  'mobile repair shops': banner('mobile-repair-shops'),
  'burger restaurants': banner('burger-restaurants'),
  'tattoo and piercing studios': banner('tattoo-and-piercing-studios'),
  'cardiology clinics': banner('cardiology-clinics'),
  'sandwich shops': banner('sandwich-shops'),
  'barbecue restaurants': banner('barbecue-restaurants'),
  'cosmetic dentistry clinics': banner('cosmetic-dentistry-clinics'),
  'beauty product suppliers': banner('beauty-product-suppliers'),
  'uniform stores': banner('uniform-stores'),
  'laundry services': banner('laundry-services'),
  'food truck stands': banner('food-truck-stands'),
  'agricultural cooperatives': banner('agricultural-cooperatives'),
  'apparel manufacturers': banner('apparel-manufacturers'),
  museums: banner('museums'),
  'diagnostic laboratories': banner('diagnostic-laboratories'),
  'hindu temples': banner('hindu-temples'),
  'grocery stores': banner('grocery-stores'),
  'doctor clinics & consultation centres': banner('doctor-clinics-consultation-centres'),
  'furniture & home decor shops': banner('furniture-home-decor-shops'),
  'industrial equipment manufacturers': banner('industrial-equipment-manufacturers'),
  'fitness gyms': banner('fitness-gyms'),
  'it services & repair': banner('it-services-repair'),
  'community centres': banner('community-centres'),
  'warehouse clubs': banner('warehouse-clubs'),
  'travel agencies': banner('travel-agencies'),
  'b2b service providers': banner('b2b-service-providers'),
  'insurance agents': banner('insurance-agents'),
  'dance classes': banner('dance-classes'),
  'two-wheeler showrooms': banner('two-wheeler-showrooms'),
  'travel agents': banner('travel-agents'),
  'cargo services': banner('cargo-services'),
  'beauty supply shops': banner('beauty-supply-shops'),
  'dermatology clinics': banner('dermatology-clinics'),
  'life insurance agents': banner('life-insurance-agents'),
  'fabric shops': banner('fabric-shops'),
  'motorcycle mechanics': banner('motorcycle-mechanics'),
  'food stores': banner('food-stores'),
  'food delivery services': banner('food-delivery-services'),
  'taxi booking services': banner('taxi-booking-services'),
  'car rental services': banner('car-rental-services'),
  'dairy farms': banner('dairy-farms'),
  'money transfer services': banner('money-transfer-services'),
  'diner restaurants': banner('diner-restaurants'),
  'book publishers': banner('book-publishers'),
  'b2b water treatment services': banner('b2b-water-treatment-services'),
  'sporting goods shops': banner('sporting-goods-shops'),
  'theatre venues': banner('theatre-venues'),
  'theme restaurants': banner('theme-restaurants'),
  'liquor shops': banner('liquor-shops'),
  'nail salons': banner('nail-salons'),
  't-shirt printers': banner('t-shirt-printers'),
  'gift shops': banner('gift-shops'),
  'immigration law firms': banner('immigration-law-firms'),
  'b2b oil and gas': banner('b2b-oil-and-gas'),
  'farmers markets': banner('farmers-markets'),
  'b2b clinical labs': banner('b2b-clinical-labs'),
  'party supply shops': banner('party-supply-shops'),
  apartments: banner('apartments'),
  'windows installation services': banner('windows-installation-services'),
  'colleges & universities': banner('colleges-universities'),
  'atm machines': banner('atm-machines'),
  'post offices & courier counters': banner('post-offices-courier-counters'),
  'educational service providers': banner('educational-service-providers'),
  'interior designers & decor studios': banner('interior-designers-decor-studios'),
  'automotive services': banner('automotive-services'),
  'vocational schools': banner('vocational-schools'),
  'industrial companies': banner('industrial-companies'),
  'event photographers': banner('event-photographers'),
  'ice cream parlours': banner('ice-cream-parlours'),
  'metal fabricators': banner('metal-fabricators'),
  'physiotherapy centres': banner('physiotherapy-centres'),
  'public libraries': banner('public-libraries'),
  'yoga centres': banner('yoga-centres'),
  'home goods shops': banner('home-goods-shops'),
  'architectural designers': banner('architectural-designers'),
  'dry cleaners': banner('dry-cleaners'),
  'train stations': banner('train-stations'),
  'fitness trainers': banner('fitness-trainers'),
  'lighting shops': banner('lighting-shops'),
  'chicken restaurants': banner('chicken-restaurants'),
  'metal suppliers': banner('metal-suppliers'),
  'vegetable vendors': banner('vegetable-vendors'),
  'smoothie juice bars': banner('smoothie-juice-bars'),
  'internet service providers': banner('internet-service-providers'),
  'granite suppliers': banner('granite-suppliers'),
  'art schools': banner('art-schools'),
  'automation services': banner('automation-services'),
  'tailors and alterations': banner('tailors-and-alterations'),
  'battery shops': banner('battery-shops'),
  'painting services': banner('painting-services'),
  'timber lumber shops': banner('timber-lumber-shops'),
  'town halls': banner('town-halls'),
  'sports clothing shops': banner('sports-clothing-shops'),
  'milk bars': banner('milk-bars'),
  'b2b tech services': banner('b2b-tech-services'),
  'furniture manufacturers': banner('furniture-manufacturers'),
  'hair replacement clinics': banner('hair-replacement-clinics'),
  'kitchen and bath stores': banner('kitchen-and-bath-stores'),
  'neurology clinics': banner('neurology-clinics'),
  'speech therapy centres': banner('speech-therapy-centres'),
  'cabin and kiosk rentals': banner('cabin-and-kiosk-rentals'),
  'craft shops': banner('craft-shops'),
  'acupuncture centres': banner('acupuncture-centres'),
  'alternative medicine centres': banner('alternative-medicine-centres'),
  'antique stores': banner('antique-stores'),
  'arabian restaurants': banner('arabian-restaurants'),
  'auto restoration services': banner('auto-restoration-services'),
  'ayurvedic stores': banner('ayurvedic-stores'),
  'beverage suppliers': banner('beverage-suppliers'),
  'bubble tea shops': banner('bubble-tea-shops'),
  'buffet restaurants': banner('buffet-restaurants'),
  'business consultants': banner('business-consultants'),
  'cable car services': banner('cable-car-services'),
  'career counselling centres': banner('career-counselling-centres'),
  'cattle breeders': banner('cattle-breeders'),
  'cinemas & entertainment': banner('cinemas-entertainment'),
  'computer wholesalers': banner('computer-wholesalers'),
  'costume stores': banner('costume-stores'),
  'craft breweries': banner('craft-breweries'),
  'drive in theatres': banner('drive-in-theatres'),
  'environmental cleanup services': banner('environmental-cleanup-services'),
  'event venues': banner('event-venues'),
  'fish farms': banner('fish-farms'),
  'funeral services': banner('funeral-services'),
  'gastropub restaurants': banner('gastropub-restaurants'),
  'gold buyers': banner('gold-buyers'),
  'hr consulting firms': banner('hr-consulting-firms'),
  'kids dentists': banner('kids-dentists'),
  'linen stores': banner('linen-stores'),
  'martial arts clubs': banner('martial-arts-clubs'),
  'masonry contractors': banner('masonry-contractors'),
  'maternity centres': banner('maternity-centres'),
  'meat wholesalers': banner('meat-wholesalers'),
  'middle eastern restaurants': banner('middle-eastern-restaurants'),
  'mills and factories': banner('mills-and-factories'),
  'mining contractors': banner('mining-contractors'),
  'oral surgeons': banner('oral-surgeons'),
  'packing services': banner('packing-services'),
  'pathology labs': banner('pathology-labs'),
  'pet breeders': banner('pet-breeders'),
  'process servers': banner('process-servers'),
  'radiology centres': banner('radiology-centres'),
  'relationship counsellors': banner('relationship-counsellors'),
  'retirement homes': banner('retirement-homes'),
  'roofing contractors': banner('roofing-contractors'),
  'shooting ranges': banner('shooting-ranges'),
  'surgery centres': banner('surgery-centres'),
  'swimming pools': banner('swimming-pools'),
  'tax lawyers': banner('tax-lawyers'),
  'trusts and ngos': banner('trusts-and-ngos'),
  'urban farms': banner('urban-farms'),
  'woodworking supply stores': banner('woodworking-supply-stores'),
  'addiction treatment centres': banner('addiction-treatment-centres'),
  'airlines & flights': banner('airlines-flights'),
  'ambulance services': banner('ambulance-services'),
  'aquarium stores': banner('aquarium-fish'),
  'architects and firms': banner('architectural-designers'),
  'b2b trade services': banner('b2b-trade-services'),
  'bike repair workshops': banner('bike-repair'),
  'boat tour operators': banner('boat-tour-operators'),
  'book and music stores': banner('book-and-music-stores'),
  'budget motels': banner('budget-lodges'),
  'donut shops': banner('donut-shops'),
  'dumpling restaurants': banner('dumpling-restaurants'),
  'educational camps': banner('educational-camps'),
  'educational supply stores': banner('school-supplies'),
  'elevator services': banner('elevator-services'),
  'ethical grocery stores': banner('organic-grocery-stores'),
  'european restaurants': banner('european-restaurants'),
  'fire stations': banner('fire-stations'),
  fishmongers: banner('fish-seafood'),
  'grain producers': banner('rice-grains'),
  'gymnastics academies': banner('gymnastics-academies'),
  'hair stylists': banner('hair-salons'),
  'health departments': banner('health-departments'),
  'hearing aid centres': banner('health-devices'),
  'hematology labs': banner('b2b-clinical-labs'),
  'hydraulic equipment suppliers': banner('industrial-equipment-manufacturers'),
  'janitorial services': banner('cleaning-services'),
  'japanese restaurants': banner('japanese-restaurants'),
  'key and locksmiths': banner('key-and-locksmiths'),
  'life coaches': banner('life-coaches'),
  'mexican restaurants': banner('mexican-restaurants'),
  'newspaper advertising agencies': banner('newspaper-advertising-agencies'),
  'nursing homes': banner('nursing-homes'),
  'oil refineries': banner('b2b-oil-and-gas'),
  'pawn brokers': banner('pawn-brokers'),
  'pharma wholesalers': banner('pharmaceutical-companies'),
  'political organizations': banner('political-organizations'),
  'print media agencies': banner('printing-press'),
  'printing equipment suppliers': banner('printing-supplies'),
  'private detective agencies': banner('private-detective-agencies'),
  'professional sports teams': banner('professional-sports-teams'),
  'rto offices': banner('rto-offices'),
  'sightseeing tour agencies': banner('sightseeing-tour-agencies'),
  'structural engineers': banner('engineering-services'),
  supermarkets: banner('grocery-stores'),
  'trophy shops': banner('trophy-shops'),
  'valuation services': banner('valuation-services'),
  'video production companies': banner('media-production-houses'),
  videographers: banner('event-photographers'),
  'water utility providers': banner('b2b-water-treatment-services'),
  'american restaurants': banner('american-restaurants'),
  'auto glass services': banner('auto-glass-services'),
  'auto insurance providers': banner('auto-insurance-providers'),
  'b2b secretarial services': banner('b2b-secretarial-services'),
  'boat services': banner('boat-services'),
  'cocktail bars': banner('cocktail-bars'),
  'commercial refrigeration': banner('commercial-refrigeration'),
  'condominium services': banner('condominium-services'),
  'cooking schools': banner('cooking-schools'),
  'coworking spaces': banner('coworking-spaces'),
  'currency exchange': banner('currency-exchange'),
  'dj services': banner('dj-services'),
  'dairy stores': banner('dairy-stores'),
  'discount stores': banner('discount-stores'),
  'divorce and family lawyers': banner('divorce-and-family-lawyers'),
  'export businesses': banner('export-businesses'),
  'fire protection services': banner('fire-protection-services'),
  'flower shops': banner('flower-shops'),
  'furniture assembly services': banner('furniture-assembly-services'),
  'garbage collection services': banner('garbage-collection-services'),
  'hookah bars': banner('hookah-bars'),
  'indo chinese restaurants': banner('indo-chinese-restaurants'),
  'industrial machine repair': banner('industrial-machine-repair'),
  'land surveying services': banner('land-surveying-services'),
  'laser hair removal': banner('laser-hair-removal'),
  'media agencies': banner('media-agencies'),
  'mortgage brokers': banner('mortgage-brokers'),
  'newspaper and magazines stores': banner('newspaper-and-magazines-stores'),
  'occupational safety consultants': banner('occupational-safety-consultants'),
  'occupational therapists': banner('occupational-therapists'),
  'outlet stores': banner('outlet-stores'),
  'pet boarding services': banner('pet-boarding-services'),
  'photo studios': banner('photo-studios'),
  'private associations': banner('private-associations'),
  'public relations agencies': banner('public-relations-agencies'),
  'public utilities': banner('public-utilities'),
  'religious schools': banner('religious-schools'),
  'security system dealers': banner('security-system-dealers'),
  'session photographers': banner('session-photographers'),
  'suppliers and distributors': banner('suppliers-and-distributors'),
  'temple forts': banner('temple-forts'),
  'temple fountains': banner('temple-fountains'),
  'textile mills': banner('textile-mills'),
  'theatre productions': banner('theatre-productions'),
  'tiling services': banner('tiling-services'),
  'toy stores': banner('toy-stores'),
  'video game stores': banner('video-game-stores'),
  'water purification services': banner('water-purification-services'),
  'well drillers': banner('well-drillers'),
  'youth clubs': banner('youth-clubs'),
  'animal shelters': banner('animal-shelters'),
  'animation studios': banner('animation-studios'),
  'asian fusion restaurants': banner('asian-restaurants'),
  'bangladeshi restaurants': banner('bangladeshi-restaurants'),
  'beer bars': banner('beer-bars'),
  'billiards clubs': banner('billiards-clubs'),
  'buddhist temples': banner('buddhist-temples'),
  'bus tour operators': banner('bus-tour-operators'),
  'car stereo stores': banner('car-stereo-stores'),
  'cement suppliers': banner('cement-suppliers'),
  'children playgrounds': banner('children-playgrounds'),
  'civic organizations': banner('civic-organizations'),
  'coal wholesale suppliers': banner('coal-wholesale-suppliers'),
  'comedy clubs': banner('comedy-clubs'),
  'cosmetics and fragrance stores': banner('cosmetics-and-fragrance-stores'),
  'courier and delivery services': banner('courier-parcel'),
  'cultural centres': banner('cultural-centres'),
  'doner kebab restaurants': banner('doner-kebab-restaurants'),
  'engine repair workshops': banner('car-repair-servicing-workshops'),
  'environmental ngos': banner('environmental-ngos'),
  'farm equipment suppliers': banner('farm-tools'),
  'food consultants': banner('food-consultants'),
  'government offices': banner('government-public-services'),
  'home theater stores': banner('tv-appliances'),
  'hotel supply stores': banner('hotel-restaurant-supplies'),
  inns: banner('inns'),
  'kids party planners': banner('kids-party-planners'),
  'korean grocery shops': banner('korean-grocery-shops'),
  'legal services': banner('legal-advocate'),
  'motorsports stores': banner('motorsports-stores'),
  'music and dvd stores': banner('music-and-dvd-stores'),
  'packers and movers': banner('packers-and-movers'),
  'packing supply stores': banner('packing-supply-stores'),
  'pet grooming centres': banner('pet-grooming-clinic'),
  'pool cleaners': banner('pool-cleaners'),
  'poultry farms': banner('poultry-farms'),
  'psychic advisors': banner('psychic-advisors'),
  'restaurant equipment suppliers': banner('restaurant-equipment-suppliers'),
  'security service providers': banner('security-service-providers'),
  'social service agencies': banner('social-service-agencies'),
  'steel fabricators': banner('steel-fabricators'),
  'tv service providers': banner('tv-appliances'),
  'tv mounting services': banner('tv-mounting-services'),
  'thai restaurants': banner('thai-restaurants'),
  'waterproofing services': banner('waterproofing-services'),
  'wedding palace venues': banner('wedding-palace-venues'),
  'weight loss centres': banner('weight-loss-centres'),
  'wholesale suppliers': banner('wholesale-distribution'),
  'wildlife sanctuaries': banner('wildlife-sanctuaries'),
  zoos: banner('zoos'),
  'soccer fields': banner('sports-facilities'),
  'child care and day care': banner('day-care-preschools'),
  'landscaping services': banner('landscaping-services'),
  'digitizing services': banner('digitizing-services'),
  'music record labels': banner('music-production-studios'),
  'telemarketing agencies': banner('telemarketing-agencies'),
  'wig shops': banner('hair-replacement-clinics'),
  'senior citizen services': banner('nursing-homes'),
};

export function premiumCategoryBanner(name?: string | null): PremiumCategoryBanner | null {
  return name ? (categoryBanners[name.trim().toLowerCase()] ?? null) : null;
}

// A business only ever carries a broad category ("Restaurants & food"), so a dosa house, a café
// and a biryani spot would all show the same restaurant banner. When the business NAME clearly
// signals a sub-type we already have a dedicated banner for, use that instead — a dosa/tiffin place
// gets the breakfast banner, a café the coffee banner, a sweet shop the mithai banner. Scoped to the
// broad food categories so a "Coffee Table" furniture shop can never pick up a café banner, and
// ordered by specificity (first match wins) with word-boundary keywords to avoid misfires.
// Name-based sub-type banners, scoped BY business category so a keyword can only fire inside the
// category it belongs to — a "Coffee Table" furniture shop can never pick up a café banner, and
// "City Eye Hospital" only matches inside Hospitals. First match within the category wins; if none
// match (or the target banner is missing) it falls back to the plain category banner. Every `key`
// here is a registered entry in `categoryBanners`.
const SUBTYPE_OVERRIDES: Readonly<Record<string, ReadonlyArray<{ test: RegExp; key: string }>>> = {
  // "Other local businesses" is the import's catch-all — a badminton academy, a gym, a coaching
  // centre and a jeweller all land here, so the category banner is meaningless. This is where name
  // detection matters most: read the actual business type from the name and pick a fitting banner.
  // Ordered by specificity — a named sport wins over the generic "academy".
  'other local businesses': [
    {
      test: /\b(badminton|cricket|football|tennis|volleyball|basketball|skating|swimming|kabaddi|athletics?|sports?|turf|stadium|arena)\b/i,
      key: 'sports, fitness & outdoors',
    },
    {
      test: /\b(gym|fitness|yoga|crossfit|zumba|aerobics|workout)\b/i,
      key: 'fitness & gym equipment',
    },
    {
      test: /\b(coaching|tuition|institute|classes|academy|iit|neet|upsc)\b/i,
      key: 'coaching-competitive',
    },
    { test: /\b(computers?|software)\b/i, key: 'computer-training' },
    { test: /\b(music|dance|karate|drawing|abacus)\b/i, key: 'music-dance-arts' },
    { test: /\b(dental|dentist)\b/i, key: 'dental-clinic' },
    { test: /\b(clinic|hospital|nursing home|diagnostic|scan)\b/i, key: 'hospitals & clinics' },
    { test: /\b(pharmacy|medical|medicals|chemist)\b/i, key: 'medical stores & pharmacies' },
    { test: /\b(salons?|parlou?r|beauty|spa)\b/i, key: 'salons & spas' },
    { test: /\b(travels?|tours?|holidays?)\b/i, key: 'travel-agency' },
    { test: /\b(caterers?|catering)\b/i, key: 'catering' },
    { test: /\b(photo\w*|studio)\b/i, key: 'photography-studio' },
    { test: /\b(real ?estate|properties|builders?|realtor)\b/i, key: 'real-estate' },
    { test: /\b(mobiles?|cellphones?)\b/i, key: 'mobile stores' },
    { test: /\b(jewell?ers?|jewell?ery)\b/i, key: 'jewellery stores' },
    { test: /\b(furnitures?)\b/i, key: 'furniture stores' },
    { test: /\b(hardware|electricals?)\b/i, key: 'hardware stores' },
    { test: /\b(hotels?|lodge|restaurants?|biryani|tiffin|dhaba)\b/i, key: 'restaurants & food' },
    { test: /\b(cafe|café|coffee)\b/i, key: 'cafe-coffee' },
    { test: /\b(bakery|bakers|cakes?)\b/i, key: 'cakes & pastries' },
    { test: /\b(sweets?|mithai)\b/i, key: 'sweets & mithai' },
  ],
  'restaurants & food': [
    { test: /\b(dosas?|tiffins?|idlis?|vadas?|udupi|breakfast)\b/i, key: 'tiffin centres' },
    { test: /\b(biryani|biriyani|dum)\b/i, key: 'biryani' },
    { test: /\b(pizza|pizzeria)\b/i, key: 'pizza' },
    { test: /\b(kfc|fried chicken|burgers?|fast ?food)\b/i, key: 'fast-food' },
    { test: /\b(chinese|noodles?|manchurian|hakka|momos?)\b/i, key: 'chinese-noodles' },
    { test: /\b(ice ?cream|gelato|kulfi|falooda|desserts?)\b/i, key: 'ice-cream-desserts' },
    { test: /\b(juices?|smoothies?|shakes?|milkshake)\b/i, key: 'juice-shakes' },
    { test: /\b(tandoor\w*|kebabs?|grill|bbq|barbeque|barbecue)\b/i, key: 'tandoor-grill' },
    { test: /\b(chaat|pani ?puri|bhel|street ?food)\b/i, key: 'chaat-street-food' },
    { test: /\b(sweets?|mithai|misthan|mishtan)\b/i, key: 'sweets & mithai' },
    { test: /\b(bakery|bakers|cakes?|pastr\w*)\b/i, key: 'cakes & pastries' },
    { test: /\b(cafe|café|coffee|barista|brew)\b/i, key: 'cafe-coffee' },
    { test: /\b(thali|punjabi|north ?indian)\b/i, key: 'north-indian-thali' },
    { test: /\b(meals|andhra|south ?indian)\b/i, key: 'south-indian-meals' },
  ],
  'hospitals & clinics': [
    { test: /\b(dental|dentist|teeth|orthodont\w*)/i, key: 'dental-clinic' },
    { test: /\b(eye|vision|optical|opthal\w*|ophthal\w*|netra)\b/i, key: 'eye-clinic' },
    { test: /\b(skin|derma\w*|cosmetolog\w*)\b/i, key: 'skin-derma-clinic' },
    {
      test: /\b(diagnostics?|labs?|laborator\w*|scans?|pathology|imaging|x-?ray)\b/i,
      key: 'diagnostic-lab',
    },
    { test: /\bphysio\w*/i, key: 'physiotherapy' },
    { test: /\b(veterinary|vet|animal)\b/i, key: 'veterinary-clinic' },
    {
      test: /\b(maternity|gyna?ec\w*|fertility|ivf|nursing home)\b/i,
      key: 'maternity-womens-clinic',
    },
    {
      test: /\b(multi ?speciality|multi ?specialty|general hospital)\b/i,
      key: 'multispeciality-hospital',
    },
  ],
  'salons & spas': [
    { test: /\b(barbers?|gents?|mens?|hair ?cutting)\b/i, key: 'mens-salon-barber' },
    {
      test: /\b(beauty ?parlou?r|ladies|womens?|bridal|makeover)\b/i,
      key: 'womens-beauty-parlour',
    },
    { test: /\b(spa|massage|ayurved\w*)\b/i, key: 'spa-massage' },
    { test: /\bnails?\b/i, key: 'nail-studio' },
  ],
  'beauty & wellness': [
    { test: /\b(spa|massage)\b/i, key: 'spa-massage' },
    { test: /\bnails?\b/i, key: 'nail-studio' },
  ],
  'tuition & coaching': [
    { test: /\b(iit|neet|eamcet|upsc|ias|coaching|academy)\b/i, key: 'coaching-competitive' },
    { test: /\b(computers?|software|typing)\b/i, key: 'computer-training' },
    { test: /\b(music|dance|abacus|arts?|drawing|karate)\b/i, key: 'music-dance-arts' },
  ],
  'education & training': [
    { test: /\b(iit|neet|upsc|coaching|academy)\b/i, key: 'coaching-competitive' },
    { test: /\b(computers?|software)\b/i, key: 'computer-training' },
    { test: /\b(music|dance|arts?|abacus)\b/i, key: 'music-dance-arts' },
  ],
  schools: [
    {
      test: /\b(pre ?school|play ?school|kinder\w*|montessori|nursery)\b/i,
      key: 'preschool-playschool',
    },
  ],
  'automobile services': [
    { test: /\b(wash|detailing)\b/i, key: 'car-wash' },
    { test: /\b(denting|painting|body ?shop)\b/i, key: 'denting-painting' },
    { test: /\b(spare ?parts?|spares|accessories)\b/i, key: 'auto-spare-parts' },
    { test: /\b(service|garage|motors|workshop)\b/i, key: 'car-service-garage' },
  ],
  'mobile stores': [
    { test: /\b(repairs?|service)\b/i, key: 'mobile-repair' },
    { test: /\b(accessories|covers?|cases?)\b/i, key: 'mobile-accessories' },
  ],
  'property services': [
    { test: /\b(real ?estate|propert\w*|realtor|builders?|estates?)\b/i, key: 'real-estate' },
  ],
  'hotels & stays': [{ test: /\b(pg|hostel|paying ?guest)\b/i, key: 'pg-hostel' }],
  'travel services': [
    { test: /\b(taxi|cabs?|car ?rental|travels)\b/i, key: 'taxi-cab-rental' },
    { test: /\b(travels?|tours?|holidays?|tourism)\b/i, key: 'travel-agency' },
  ],
  'event services': [
    { test: /\b(catering|caterers?)\b/i, key: 'catering' },
    { test: /\b(decor\w*|florist|flowers?)\b/i, key: 'event-decoration' },
    { test: /\b(photo\w*|studio|videograph\w*)\b/i, key: 'photography-studio' },
    { test: /\b(tent|mandap|function ?hall)\b/i, key: 'tent-house-rental' },
  ],
  'home services': [
    {
      test: /\b(ac|air ?con\w*|appliance|refrigerat\w*|washing ?machine)\b/i,
      key: 'ac-appliance-repair',
    },
    { test: /\b(carpent\w*|woodwork|furniture)\b/i, key: 'carpentry-woodwork' },
    { test: /\b(painting|painters?)\b/i, key: 'painting-service' },
    { test: /\b(cleaning|pest ?control)\b/i, key: 'deep-cleaning-pest' },
  ],
  'cleaning services': [
    { test: /\b(pest ?control|deep ?cleaning|cleaning)\b/i, key: 'deep-cleaning-pest' },
  ],
  'professional services': [
    {
      test: /\b(chartered ?accountant|accounting|accounts?|tax|\bca\b|audit\w*)\b/i,
      key: 'accounting-ca',
    },
    { test: /\b(advocate|lawyer|legal|law\b)\b/i, key: 'legal-advocate' },
    { test: /\b(insurance|finance|loans?|investment\w*)\b/i, key: 'insurance-finance' },
    { test: /\b(architect\w*|interior\w*|design\w*)\b/i, key: 'architect-interior' },
  ],
  'printing & stationery': [
    { test: /\b(flex|banners?|signage|vinyl|hoarding)\b/i, key: 'flex-banner-signage' },
    { test: /\b(printing|printers?|press|xerox|offset)\b/i, key: 'printing-press' },
  ],
  'pet stores & services': [
    { test: /\b(grooming|clinic|vet)\b/i, key: 'pet-grooming-clinic' },
    { test: /\b(aquarium|fish|aquatic)\b/i, key: 'aquarium-fish' },
  ],
  'clothing stores': [
    { test: /\b(sarees?|saris?|ethnic|silks?)\b/i, key: 'sarees & ethnic wear' },
    { test: /\b(kids|childrens?|baby)\b/i, key: 'kids clothing' },
    { test: /\b(footwear|shoes?|chappals?|sandals?)\b/i, key: 'footwear' },
    { test: /\b(ladies|womens?)\b/i, key: 'womens clothing' },
    { test: /\b(gents?|mens?)\b/i, key: 'mens clothing' },
  ],
  'jewellery stores': [
    { test: /\b(imitation|artificial|fashion)\b/i, key: 'jewellery & imitation' },
  ],
};

/**
 * The banner for a specific business: a name-based sub-type refinement over the plain category
 * banner, scoped to the business's category so it can never misfire across categories. Falls back
 * to the category banner (then the monogram) when the name says nothing specific — so it never
 * shows a worse banner than before, only a more fitting one.
 */
/** Words that appear in half the category names and so identify nothing. */
const UNHELPFUL = new Set([
  'shop',
  'shops',
  'store',
  'stores',
  'centre',
  'centres',
  'center',
  'centers',
  'service',
  'services',
  'business',
  'businesses',
  'local',
  'other',
  'and',
  // "IT Services & Repair" was taking the bike-repair banner, because 'repair'
  // was the only word the two shared. These are verbs a dozen unrelated trades
  // have in common; they say what a business does, not what it looks like.
  'repair',
  'repairs',
  'supply',
  'supplies',
  'dealer',
  'dealers',
  'agency',
  'agencies',
  'general',
  'goods',
  'works',
  'point',
  'house',
  'company',
]);

/**
 * Head nouns too generic to decide a match on their own.
 *
 * The head-noun rule is right in principle and wrong for these, because they
 * name a shape of business rather than a trade, and unrelated trades land on
 * the same word:
 *
 *   Dental clinics & tooth CARE centres  -> hair CARE
 *   Police STATIONS                      -> ev charging STATIONS
 *   Building MATERIAL shops              -> fabric & tailoring MATERIAL
 *
 * A dentist was being illustrated with combs and hair oil. These words may
 * still count toward a two-word match, where a second word does the work -
 * they just cannot carry a match by themselves.
 */
const GENERIC_HEADS = new Set([
  'care',
  'station',
  'stations',
  'material',
  'materials',
  'equipment',
  'products',
  'solutions',
  'systems',
  'items',
  'accessories',
  'training',
  'institute',
  'institutes',
]);

/**
 * The nearest banner by shared words, for a category the catalogue has never heard of.
 *
 * The catalogue is keyed by the 45 category names the directory had when the artwork was
 * made. It now has 69 parents and 1,375 subcategories, so "Spas & wellness centres" — a real
 * category with real businesses in it — matched nothing and the storefront rendered a plain
 * dark panel where its photograph should be.
 *
 * Matching on shared words finds "beauty & wellness" for that, and keeps working for
 * categories added later without anybody having to remember this file exists. Words like
 * "store" and "services" are ignored: they appear in half the names and would match anything.
 */
function nearestBannerByWords(categoryName: string): PremiumCategoryBanner | null {
  const words = categoryName
    .toLowerCase()
    .split(/[^a-z]+/)
    .filter((word) => word.length >= 4 && !UNHELPFUL.has(word));
  if (words.length === 0) return null;

  let best: { key: string; score: number } | null = null;
  for (const key of Object.keys(categoryBanners)) {
    const keyWords = key
      .split(/[^a-z]+/)
      .filter((word) => word.length >= 4 && !UNHELPFUL.has(word));
    const shared = keyWords.filter((word) => words.includes(word));
    const score = shared.length;
    // It is not how many words two names share, it is which one.
    //
    //   Theme restaurants  <- Indian restaurants   share 'restaurants'  good
    //   Home developers    <- Home & kitchen       share 'home'         wrong
    //
    // Both are one word. The difference is that 'restaurants' is the head noun
    // of each name - the thing the business actually is - while 'home' is only
    // a modifier on one side. In English the head noun is the last significant
    // word, so a single shared word counts only when it ends both names. A
    // modifier in common is a coincidence, and a coincidence showed a property
    // builder a rack of wooden spoons.
    const head = words[words.length - 1];
    const headMatches =
      score > 0 &&
      head === keyWords[keyWords.length - 1] &&
      shared.includes(head) &&
      !GENERIC_HEADS.has(head);
    if ((score >= 2 || headMatches) && (!best || score > best.score)) best = { key, score };
  }
  return best ? (categoryBanners[best.key] ?? null) : null;
}

export function premiumBusinessBanner(
  name?: string | null,
  categoryName?: string | null,
): PremiumCategoryBanner | null {
  const category = categoryName?.trim().toLowerCase();
  const overrides = category ? SUBTYPE_OVERRIDES[category] : undefined;
  if (name && overrides) {
    for (const { test, key } of overrides) {
      if (test.test(name) && categoryBanners[key]) return categoryBanners[key]!;
    }
  }
  return (
    premiumCategoryBanner(categoryName) ??
    (categoryName ? nearestBannerByWords(categoryName) : null)
  );
}
