export type PremiumCategoryBanner = Readonly<{
  desktop: string;
  mobile: string;
}>;

function banner(slug: string): PremiumCategoryBanner {
  return {
    desktop: `/banners/categories/${slug}-desktop.webp`,
    mobile: `/banners/categories/${slug}-mobile.webp`,
  };
}

const automobile = banner('automobile-services-v2');
const beauty = banner('beauty-wellness-v2');
const education = banner('education-training');

const categoryBanners: Readonly<Record<string, PremiumCategoryBanner>> = {
  'automobile services': automobile,
  'ayurveda & herbal': banner('ayurveda-herbal'),
  'bakeries & sweets': banner('bakeries-sweets-v5'),
  'bread & buns': banner('bread-buns'),
  'beauty & cosmetics': banner('beauty-cosmetics'),
  'beauty & wellness': beauty,
  'bike repair': banner('bike-repair'),
  'books, stationery & office': banner('books-stationery'),
  'cakes & pastries': banner('cakes-pastries'),
  'car repair': banner('car-repair'),
  chicken: banner('chicken'),
  'cleaning services': banner('cleaning-services'),
  'clothing stores': banner('clothing-stores'),
  colleges: banner('colleges'),
  'computer & laptop stores': banner('computer-laptop-stores'),
  'cooking oil & ghee': banner('cooking-oil-ghee'),
  'courier & parcel': banner('courier-parcel'),
  'dairy, bakery & eggs': banner('dairy-bakery-eggs'),
  'dry fruits & nuts': banner('dry-fruits-nuts'),
  eggs: banner('eggs'),
  'education & training': education,
  'electrical services': banner('electrical-services'),
  'electrical stores': banner('electrical-stores'),
  'electronics stores': banner('electronics-stores'),
  'event services': banner('event-services'),
  'ev charging stations': banner('ev-charging-stations'),
  'flour & atta': banner('flour-atta'),
  'fish & seafood': banner('fish-seafood'),
  'footwear stores': banner('footwear-stores'),
  'furniture stores': banner('furniture-stores'),
  'fruits & vegetables': banner('fruits-vegetables'),
  'gift stores': banner('gift-stores'),
  'groceries & provisions': banner('groceries-provisions'),
  'grocery & kirana': banner('grocery-kirana'),
  'hair care': banner('hair-care'),
  'hardware stores': banner('hardware-stores'),
  'health & personal care': banner('health-personal-care'),
  'home & kitchen': banner('home-kitchen'),
  'home services': banner('home-services'),
  'hospitals & clinics': banner('hospitals-clinics'),
  'hotels & stays': banner('hotels-stays'),
  'jewellery stores': banner('jewellery-stores'),
  'local manufacturers': banner('local-manufacturers'),
  'meat, fish & poultry': banner('meat-fish-poultry'),
  'medical stores & pharmacies': banner('medical-pharmacies'),
  'medicines & pharmacy': banner('medicines-pharmacy'),
  'mens clothing': banner('mens-clothing'),
  'milk, curd & butter': banner('milk-curd'),
  'mobile stores': banner('mobile-stores'),
  'mutton & goat': banner('mutton'),
  'perfumes & fragrances': banner('fragrances'),
  'pet stores & services': banner('pet-services'),
  'petrol stations': banner('petrol-pumps'),
  'pickles & papads': banner('pickles-papads'),
  'paneer & cheese': banner('paneer-cheese'),
  'plumbing services': banner('plumbing-services'),
  'printing & stationery': banner('printing-stationery'),
  'professional services': banner('professional-services'),
  'processed & frozen meat': banner('processed-meat'),
  'property services': banner('property-services'),
  'pulses & dals': banner('pulses-dals'),
  'ready to cook & instant': banner('ready-to-cook'),
  'repair services': banner('repair-services'),
  'rice & grains': banner('rice-grains'),
  'restaurants & food': banner('restaurants-food'),
  'salons & spas': banner('salons-spas'),
  schools: banner('schools'),
  'skin care': banner('skin-care'),
  'snacks & namkeen': banner('snacks-namkeen'),
  'spices & masalas': banner('spices-masalas'),
  'sports, fitness & outdoors': banner('sports-fitness-outdoors'),
  'sugar, salt & jaggery': banner('sugar-salt-jaggery'),
  'sweets & mithai': banner('sweets-mithai'),
  'tailoring & boutiques': banner('tailoring-services'),
  'tea, coffee & beverages': banner('tea-coffee-beverages'),
  'tiffin centres': banner('tiffin-centres-v2'),
  'toys, baby & kids': banner('toys-baby-kids'),
  'travel services': banner('travel-transport'),
  'tuition & coaching': banner('tuition-coaching'),
  'tyre & battery stores': banner('tyre-battery-stores'),
  'wholesale businesses': banner('wholesale-distribution'),
  'womens clothing': banner('womens-clothing'),
  'fresh vegetables': banner('fresh-vegetables'),
  'fresh fruits': banner('fresh-fruits'),
  'leafy greens & herbs': banner('leafy-greens'),
  'organic produce': banner('organic-produce'),
  'bath & body': banner('bath-body'),
  'oral care': banner('oral-care'),
  'health devices': banner('health-devices'),
  'supplements & nutrition': banner('supplements'),
  'sanitary & hygiene': banner('sanitary-hygiene'),
  makeup: banner('makeup'),
  grooming: banner('grooming'),
  'salon & spa products': banner('salon-supplies'),
  'clothing & footwear': banner('clothing-footwear'),
  'sarees & ethnic wear': banner('sarees-ethnic'),
  'kids clothing': banner('kids-clothing'),
  footwear: banner('footwear'),
  'bags & luggage': banner('bags-luggage'),
  'watches & accessories': banner('watches-accessories'),
  'jewellery & imitation': banner('jewellery'),
  'fabric & tailoring material': banner('fabric-tailoring'),
  'cookware & utensils': banner('cookware-utensils'),
  'storage & containers': banner('storage-containers'),
  'cleaning & detergents': banner('cleaning-supplies'),
  'home decor': banner('home-decor'),
  'bedding & curtains': banner('bedding-curtains'),
  'lighting & electricals': banner('lighting-electricals'),
  'gas stoves & cylinders': banner('gas-stoves'),
  'plastic & steelware': banner('plastic-steel-ware'),
  books: banner('books'),
  'school supplies': banner('school-supplies'),
  'office stationery': banner('office-stationery'),
  'art & craft': banner('art-craft'),
  'printing & xerox material': banner('printing-supplies'),
  'sports equipment': banner('sports-equipment'),
  'fitness & gym equipment': banner('fitness-gym'),
  'cycles & accessories': banner('cycles'),
  'outdoor & camping': banner('outdoor-camping'),
  'toys & games': banner('toys-games'),
  'baby gear': banner('baby-gear'),
  'baby food & diapers': banner('baby-food-diapers'),
  'pets & pet supplies': banner('pets-supplies'),
  'pet food': banner('pet-food'),
  'pet accessories': banner('pet-accessories'),
  'pets & livestock': banner('pets-livestock'),
  'farm, garden & agriculture': banner('farm-garden'),
  'seeds & saplings': banner('seeds-saplings'),
  'fertilizers & pesticides': banner('fertilizers-pesticides'),
  'farm tools & machinery': banner('farm-tools'),
  'plants & nursery': banner('plants-nursery'),
  'garden supplies': banner('garden-supplies'),
  'farm produce (bulk)': banner('farm-produce-bulk'),
  'hardware, tools & building': banner('hardware-tools'),
  'hand tools': banner('hand-tools'),
  'power tools': banner('power-tools'),
  'paints & finishes': banner('paints'),
  'plumbing & sanitary': banner('plumbing-sanitary'),
  'cement, steel & building materials': banner('building-materials'),
  'electrical supplies': banner('electrical-supplies'),
  'industrial & business supplies': banner('industrial-supplies'),
  'packaging material': banner('packaging'),
  'safety equipment': banner('safety-equipment'),
  'machinery & equipment': banner('machinery'),
  'hotel & restaurant supplies': banner('hotel-restaurant-supplies'),
  'raw materials': banner('raw-materials'),
  'musical instruments & hobby': banner('music-hobby'),
  'musical instruments': banner('musical-instruments'),
  'handicrafts & handmade': banner('handicrafts'),
  'collectibles & antiques': banner('collectibles'),
  'religious & festive': banner('religious-festive'),
  'pooja items': banner('pooja-items'),
  'festival decorations': banner('festival-decor'),
  'gifts & novelties': banner('gifts'),
  'agricultural supplies': banner('agricultural-supplies'),
  'other local businesses': banner('other-local-businesses'),
  electronics: banner('electronics'),
  'mobile phones': banner('mobile-phones'),
  'laptops & computers': banner('laptops-computers'),
  'tv & appliances': banner('tv-appliances'),
  vehicles: banner('vehicles'),
  cars: banner('cars'),
  'motorcycles & scooters': banner('motorcycles-scooters'),
  'furniture & home': banner('furniture-home'),
  jobs: banner('jobs'),
  'it & software': banner('jobs-it-software'),
  'sales & marketing': banner('jobs-sales-marketing'),
  'delivery & driver': banner('jobs-delivery-driver'),
  'retail & hospitality': banner('jobs-retail-hospitality'),
  services: banner('services'),
  'home repair': banner('services-home-repair'),
  'tuition & classes': banner('services-tuition'),
  'health & beauty': banner('services-health-beauty'),
  'real estate & rentals': banner('real-estate-rentals'),
  'local offers': banner('local-offers'),
  'salons & spa': banner('offers-salons-spa'),
  shopping: banner('offers-shopping'),
  businesses: banner('businesses'),
  restaurants: banner('business-restaurants'),
  'clinics & hospitals': banner('business-clinics'),
  'shops & retail': banner('business-shops'),
  events: banner('events'),
};

export function premiumCategoryBanner(name?: string | null): PremiumCategoryBanner | null {
  return name ? (categoryBanners[name.trim().toLowerCase()] ?? null) : null;
}

// A business only ever carries a broad category ("Restaurants & food"), so a dosa house, a café
// and a biryani spot would all show the same restaurant banner. When the business NAME clearly
// signals a sub-type we already have a dedicated banner for, use that instead — a dosa/tiffin place
// gets the breakfast banner, a café the coffee banner, a sweet shop the mithai banner. Scoped to the
// broad food categories so a "Coffee Table" furniture shop can never pick up a café banner, and
// ordered by specificity (first match wins) with word-boundary keywords to avoid misfires.
const NAME_BANNER_OVERRIDES: ReadonlyArray<{ test: RegExp; key: string }> = [
  { test: /\b(dosa|tiffin|tiffins|idli|vada|udupi|breakfast)\b/i, key: 'tiffin centres' },
  { test: /\b(sweets?|mithai|misthan|mishtan)\b/i, key: 'sweets & mithai' },
  { test: /\b(bakery|bakers|cake|cakes|pastr\w*)\b/i, key: 'cakes & pastries' },
  { test: /\b(cafe|café|coffee|barista|brew)\b/i, key: 'tea, coffee & beverages' },
];
const NAME_OVERRIDE_CATEGORIES = new Set(['restaurants & food', 'grocery & kirana']);

/**
 * The banner for a specific business: a name-based sub-type refinement over the plain category
 * banner. Falls back to the category banner (and then the monogram) when the name says nothing
 * specific — so it never shows a worse banner than before, only a more fitting one.
 */
export function premiumBusinessBanner(
  name?: string | null,
  categoryName?: string | null,
): PremiumCategoryBanner | null {
  const category = categoryName?.trim().toLowerCase();
  if (name && category && NAME_OVERRIDE_CATEGORIES.has(category)) {
    for (const { test, key } of NAME_BANNER_OVERRIDES) {
      if (test.test(name) && categoryBanners[key]) return categoryBanners[key]!;
    }
  }
  return premiumCategoryBanner(categoryName);
}
